--------------------------------------------------------
--  DDL for Table CSCO_CGN_STATS_IBHW
--------------------------------------------------------

  CREATE TABLE CSCO_CGN_STATS_IBHW 
   (	FECHA DATE, 
	NODE VARCHAR2(255 CHAR), 
	CGNINSTANCEID VARCHAR2(10 CHAR), 
	ACTIVETRANSLATIONS NUMBER(15,2), 
	CREATERATE NUMBER(15,2), 
	DELETERATE NUMBER(15,2), 
	OUTSIDEFORWARDRATE NUMBER(15,2), 
	INSIDEFORWARDRATE NUMBER(15,2), 
	DROPSPORTLIMITEXCEEDED NUMBER(15,2), 
	DROPSSYSTEMLIMITREACHED NUMBER(15,2), 
	DROPSRESOURCEDEPLETION NUMBER(15,2), 
	NOTRANSLATIONENTRYDROPS NUMBER(15,2), 
	ADDRESSTOTALLYFREE NUMBER(15,2), 
	ADDRESSUSED NUMBER(15,2), 
	NUMBEROFSUBSCRIBERS NUMBER(15,2)
   ) 
 NOCOMPRESS NOLOGGING
  TABLESPACE TBS_SUMMARY ;

   COMMENT ON COLUMN CSCO_CGN_STATS_IBHW.FECHA IS 'Reemplazo de la columna TIMESTAMP por ser palabra reservada';
--------------------------------------------------------
--  DDL for Index CSCO_CGN_STATS_IBHW_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX CSCO_CGN_STATS_IBHW_PK ON CSCO_CGN_STATS_IBHW (FECHA, NODE, CGNINSTANCEID) 
  TABLESPACE TBS_SUMMARY ;
--------------------------------------------------------
--  Constraints for Table CSCO_CGN_STATS_IBHW
--------------------------------------------------------

  ALTER TABLE CSCO_CGN_STATS_IBHW MODIFY (CREATERATE NOT NULL ENABLE);
  ALTER TABLE CSCO_CGN_STATS_IBHW MODIFY (ACTIVETRANSLATIONS NOT NULL ENABLE);
  ALTER TABLE CSCO_CGN_STATS_IBHW MODIFY (CGNINSTANCEID NOT NULL ENABLE);
  ALTER TABLE CSCO_CGN_STATS_IBHW MODIFY (NODE NOT NULL ENABLE);
  ALTER TABLE CSCO_CGN_STATS_IBHW MODIFY (FECHA NOT NULL ENABLE);
  ALTER TABLE CSCO_CGN_STATS_IBHW ADD CONSTRAINT CSCO_CGN_STATS_IBHW_PK PRIMARY KEY (FECHA, NODE, CGNINSTANCEID)  ENABLE;
  ALTER TABLE CSCO_CGN_STATS_IBHW MODIFY (NUMBEROFSUBSCRIBERS NOT NULL ENABLE);
  ALTER TABLE CSCO_CGN_STATS_IBHW MODIFY (ADDRESSUSED NOT NULL ENABLE);
  ALTER TABLE CSCO_CGN_STATS_IBHW MODIFY (ADDRESSTOTALLYFREE NOT NULL ENABLE);
  ALTER TABLE CSCO_CGN_STATS_IBHW MODIFY (NOTRANSLATIONENTRYDROPS NOT NULL ENABLE);
  ALTER TABLE CSCO_CGN_STATS_IBHW MODIFY (DROPSRESOURCEDEPLETION NOT NULL ENABLE);
  ALTER TABLE CSCO_CGN_STATS_IBHW MODIFY (DROPSSYSTEMLIMITREACHED NOT NULL ENABLE);
  ALTER TABLE CSCO_CGN_STATS_IBHW MODIFY (DROPSPORTLIMITEXCEEDED NOT NULL ENABLE);
  ALTER TABLE CSCO_CGN_STATS_IBHW MODIFY (INSIDEFORWARDRATE NOT NULL ENABLE);
  ALTER TABLE CSCO_CGN_STATS_IBHW MODIFY (OUTSIDEFORWARDRATE NOT NULL ENABLE);
  ALTER TABLE CSCO_CGN_STATS_IBHW MODIFY (DELETERATE NOT NULL ENABLE);
