
DROP TABLE CSCO_LINKS PURGE;

  CREATE TABLE CSCO_LINKS 
   (	ELEMENT_ID NUMBER, 
	ELEMENT_ALIASES VARCHAR2(500 CHAR) NOT NULL ENABLE, 
	VALID_START_DATE DATE, 
	VALID_FINISH_DATE DATE, 
	TIPO VARCHAR2(40 CHAR), 
	EQUIPO_A VARCHAR2(255 CHAR), 
	INTERFACE_A VARCHAR2(255 CHAR), 
	EQUIPO_B VARCHAR2(255 CHAR), 
	INTERFACE_B VARCHAR2(255 CHAR), 
	ORIGEN VARCHAR2(40 CHAR), 
	DESTINO VARCHAR2(40 CHAR), 
	FLAG_ENABLED CHAR(1 CHAR), 
	GRUPO VARCHAR2(50 CHAR), 
	PAIS VARCHAR2(20 CHAR), 
	ELEMENT_TYPE VARCHAR2(20 CHAR), 
	ELEMENT_NAME VARCHAR2(20 CHAR), 
	INTERFACE_NAME VARCHAR2(100 CHAR), 
	GROUP_TYPE VARCHAR2(20 CHAR), 
	ELEMENT_IP VARCHAR2(15 CHAR), 
	NOMBRE_GRUPO VARCHAR2(50 CHAR), 
	FRONTERA VARCHAR2(30 CHAR), 
	BORDE VARCHAR2(50 CHAR), 
	SPEED_MODIFY NUMBER
  )NOLOGGING NOCOMPRESS
	TABLESPACE TBS_AUXILIAR ;
  
  ALTER TABLE CSCO_LINKS ADD CONSTRAINT CSCO_LINKS_PK PRIMARY KEY (ELEMENT_ALIASES) ENABLE;
  

   COMMENT ON TABLE CSCO_LINKS  IS 'Vinculos Cisco Prime';

CREATE PUBLIC SYNONYM CSCO_LINKS FOR SMART.CSCO_LINKS;

GRANT INSERT, UPDATE, SELECT ON CSCO_LINKS TO CTI2522;
GRANT INSERT, UPDATE, SELECT ON CSCO_LINKS TO CTI22041;