--------------------------------------------------------
--  DDL for Table CSCO_INVENTORY
--------------------------------------------------------

  CREATE TABLE CSCO_INVENTORY 
   (	INVENTORY_ID VARCHAR2(32 CHAR), 
	DEVICE VARCHAR2(255 CHAR), 
	DEVICE_SERIES VARCHAR2(255 CHAR), 
	ELEMENT_TYPE VARCHAR2(255 CHAR), 
	IP_ADDRESS VARCHAR2(255 CHAR)
   ) NOCOMPRESS NOLOGGING
  TABLESPACE TBS_AUXILIAR ;

   COMMENT ON COLUMN CSCO_INVENTORY.INVENTORY_ID IS 'STANDARD_HASH(MD5) aplicado a la columna device para ser utilizado como PK';
   COMMENT ON COLUMN CSCO_INVENTORY.DEVICE_SERIES IS 'Reescritura de la columna DEVICE SERIES';
   COMMENT ON COLUMN CSCO_INVENTORY.ELEMENT_TYPE IS 'Reescritura de la columna ELEMENT TYPE';
   COMMENT ON COLUMN CSCO_INVENTORY.IP_ADDRESS IS 'Reescritura de la columna IP ADDRESS por ser palabra reservada';
--------------------------------------------------------
--  DDL for Index PK_CSCO_INVENTORY
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_CSCO_INVENTORY ON CSCO_INVENTORY (INVENTORY_ID) 
  TABLESPACE TBS_AUXILIAR ;
--------------------------------------------------------
--  Constraints for Table CSCO_INVENTORY
--------------------------------------------------------

  ALTER TABLE CSCO_INVENTORY ADD CONSTRAINT PK_CSCO_INVENTORY PRIMARY KEY (INVENTORY_ID) ENABLE;
  ALTER TABLE CSCO_INVENTORY MODIFY (IP_ADDRESS NOT NULL ENABLE);
  ALTER TABLE CSCO_INVENTORY MODIFY (ELEMENT_TYPE NOT NULL ENABLE);
  ALTER TABLE CSCO_INVENTORY MODIFY (DEVICE_SERIES NOT NULL ENABLE);
  ALTER TABLE CSCO_INVENTORY MODIFY (DEVICE NOT NULL ENABLE);
  ALTER TABLE CSCO_INVENTORY MODIFY (INVENTORY_ID NOT NULL ENABLE);
