--------------------------------------------------------
--  DDL for Table CSCO_INTERFACE_HOUR
--------------------------------------------------------

  CREATE TABLE CSCO_INTERFACE_HOUR 
   (	FECHA DATE, 
	NODE VARCHAR2(255 CHAR), 
	INTERFAZ VARCHAR2(255 CHAR), 
	IFINDEX NUMBER, 
	IFTYPE NUMBER, 
	IFSPEED NUMBER(24,2), 
	SENDUTIL NUMBER(24,2), 
	SENDTOTALPKTS NUMBER, 
	SENDTOTALPKTRATE NUMBER(24,2), 
	SENDBYTES NUMBER, 
	SENDBYTERATE NUMBER(24,2), 
	SENDBITRATE NUMBER(24,2), 
	SENDUCASTPKTPERCENT NUMBER(24,2), 
	SENDMCASTPKTPERCENT NUMBER(24,2), 
	SENDBCASTPKTPERCENT NUMBER(24,2), 
	SENDERRORS NUMBER(24,2), 
	SENDERRORPERCENT NUMBER(24,2), 
	SENDDISCARDS NUMBER(24,2), 
	SENDDISCARDPERCENT NUMBER(24,2), 
	RECEIVEUTIL NUMBER(24,2), 
	RECEIVETOTALPKTS NUMBER(24,2), 
	RECEIVETOTALPKTRATE NUMBER(24,2), 
	RECEIVEBYTES NUMBER(24,2), 
	RECEIVEBYTERATE NUMBER(24,2), 
	RECEIVEBITRATE NUMBER(24,2), 
	RECEIVEUCASTPKTPERCENT NUMBER(24,2), 
	RECEIVEMCASTPKTPERCENT NUMBER(24,2), 
	RECEIVEBCASTPKTPERCENT NUMBER(24,2), 
	RECEIVEERRORS NUMBER(24,2), 
	RECEIVEERRORPERCENT NUMBER(24,2), 
	RECEIVEDISCARDS NUMBER(24,2), 
	RECEIVEDISCARDPERCENT NUMBER(24,2), 
	SENDBCASTPKTRATE NUMBER(24,2), 
	RECEIVEBCASTPKTRATE NUMBER(24,2), 
	IFTYPESTRING VARCHAR2(255 CHAR),
  MAX_SEND_RECEIVE as (GREATEST(NVL(SENDBYTES,0),NVL(RECEIVEBYTES,0)))
   ) NOCOMPRESS NOLOGGING
  PARTITION BY RANGE (FECHA)
  INTERVAL (NUMTOYMINTERVAL(1, 'HOUR'))
  (
  PARTITION INTERFACEHOUR2016101800 VALUES LESS THAN (TO_DATE('2016.10.18 01','YYYY.MM.DD HH24')) TABLESPACE DEVELOPER PCTFREE 10 PCTUSED 80
  )
  TABLESPACE DEVELOPER ;

   COMMENT ON COLUMN CSCO_INTERFACE_HOUR.FECHA IS 'Reemplazo del nombre TIMESTAMP por ser palabra reservada';
   COMMENT ON COLUMN CSCO_INTERFACE_HOUR.INTERFAZ IS 'Reemplazo del nombre INTERFACE por ser palabra reservada';
--------------------------------------------------------
--  DDL for Index IDX_INTERFACE_HOUR
--------------------------------------------------------

  CREATE INDEX IDX_INTERFACE_HOUR ON CSCO_INTERFACE_HOUR (FECHA, NODE, INTERFAZ) LOCAL
  TABLESPACE DEVELOPER ;
--------------------------------------------------------
--  DDL for Index IDX_INTERFACE_HOUR_FECHA
--------------------------------------------------------

  CREATE INDEX IDX_INTERFACE_HOUR_FECHA ON CSCO_INTERFACE_HOUR (TO_CHAR(FECHA,'DD.MM.YYYY') DESC) LOCAL
  TABLESPACE DEVELOPER ;
--------------------------------------------------------
--  Constraints for Table CSCO_INTERFACE_HOUR
--------------------------------------------------------

  ALTER TABLE CSCO_INTERFACE_HOUR MODIFY (IFTYPESTRING NOT NULL ENABLE);
  ALTER TABLE CSCO_INTERFACE_HOUR MODIFY (RECEIVEBCASTPKTRATE NOT NULL ENABLE);
  ALTER TABLE CSCO_INTERFACE_HOUR MODIFY (SENDBCASTPKTRATE NOT NULL ENABLE);
  ALTER TABLE CSCO_INTERFACE_HOUR MODIFY (RECEIVEDISCARDPERCENT NOT NULL ENABLE);
  ALTER TABLE CSCO_INTERFACE_HOUR MODIFY (RECEIVEDISCARDS NOT NULL ENABLE);
  ALTER TABLE CSCO_INTERFACE_HOUR MODIFY (RECEIVEERRORPERCENT NOT NULL ENABLE);
  ALTER TABLE CSCO_INTERFACE_HOUR MODIFY (RECEIVEERRORS NOT NULL ENABLE);
  ALTER TABLE CSCO_INTERFACE_HOUR MODIFY (RECEIVEBCASTPKTPERCENT NOT NULL ENABLE);
  ALTER TABLE CSCO_INTERFACE_HOUR MODIFY (RECEIVEMCASTPKTPERCENT NOT NULL ENABLE);
  ALTER TABLE CSCO_INTERFACE_HOUR MODIFY (RECEIVEUCASTPKTPERCENT NOT NULL ENABLE);
  ALTER TABLE CSCO_INTERFACE_HOUR MODIFY (RECEIVEBITRATE NOT NULL ENABLE);
  ALTER TABLE CSCO_INTERFACE_HOUR MODIFY (RECEIVEBYTERATE NOT NULL ENABLE);
  ALTER TABLE CSCO_INTERFACE_HOUR MODIFY (RECEIVEBYTES NOT NULL ENABLE);
  ALTER TABLE CSCO_INTERFACE_HOUR MODIFY (RECEIVETOTALPKTRATE NOT NULL ENABLE);
  ALTER TABLE CSCO_INTERFACE_HOUR MODIFY (RECEIVETOTALPKTS NOT NULL ENABLE);
  ALTER TABLE CSCO_INTERFACE_HOUR MODIFY (RECEIVEUTIL NOT NULL ENABLE);
  ALTER TABLE CSCO_INTERFACE_HOUR MODIFY (SENDDISCARDPERCENT NOT NULL ENABLE);
  ALTER TABLE CSCO_INTERFACE_HOUR MODIFY (SENDDISCARDS NOT NULL ENABLE);
  ALTER TABLE CSCO_INTERFACE_HOUR MODIFY (SENDERRORPERCENT NOT NULL ENABLE);
  ALTER TABLE CSCO_INTERFACE_HOUR MODIFY (SENDERRORS NOT NULL ENABLE);
  ALTER TABLE CSCO_INTERFACE_HOUR MODIFY (SENDBCASTPKTPERCENT NOT NULL ENABLE);
  ALTER TABLE CSCO_INTERFACE_HOUR MODIFY (SENDMCASTPKTPERCENT NOT NULL ENABLE);
  ALTER TABLE CSCO_INTERFACE_HOUR MODIFY (SENDUCASTPKTPERCENT NOT NULL ENABLE);
  ALTER TABLE CSCO_INTERFACE_HOUR MODIFY (SENDBITRATE NOT NULL ENABLE);
  ALTER TABLE CSCO_INTERFACE_HOUR MODIFY (SENDBYTERATE NOT NULL ENABLE);
  ALTER TABLE CSCO_INTERFACE_HOUR MODIFY (SENDBYTES NOT NULL ENABLE);
  ALTER TABLE CSCO_INTERFACE_HOUR MODIFY (SENDTOTALPKTRATE NOT NULL ENABLE);
  ALTER TABLE CSCO_INTERFACE_HOUR MODIFY (SENDTOTALPKTS NOT NULL ENABLE);
  ALTER TABLE CSCO_INTERFACE_HOUR MODIFY (SENDUTIL NOT NULL ENABLE);
  ALTER TABLE CSCO_INTERFACE_HOUR MODIFY (IFSPEED NOT NULL ENABLE);
  ALTER TABLE CSCO_INTERFACE_HOUR MODIFY (IFTYPE NOT NULL ENABLE);
  ALTER TABLE CSCO_INTERFACE_HOUR MODIFY (IFINDEX NOT NULL ENABLE);
  ALTER TABLE CSCO_INTERFACE_HOUR MODIFY (INTERFAZ NOT NULL ENABLE);
  ALTER TABLE CSCO_INTERFACE_HOUR MODIFY (NODE NOT NULL ENABLE);
  ALTER TABLE CSCO_INTERFACE_HOUR MODIFY (FECHA NOT NULL ENABLE);
  ALTER TABLE CSCO_INTERFACE_HOUR ADD CONSTRAINT CSCO_INTERFACE_HOUR_PK PRIMARY KEY (FECHA, NODE, INTERFAZ)  ENABLE;
