--------------------------------------------------------
--  DDL for Table CSCO_CPU_MEM_DEVICE_AVG_HOUR
--------------------------------------------------------

  CREATE TABLE CSCO_CPU_MEM_DEVICE_AVG_HOUR 
   (	FECHA DATE, 
	NODE VARCHAR2(255 CHAR), 
	CPUUTILMAX5MINDEVICEAVG NUMBER(15,2), 
	CPUUTILAVG5MINDEVICEAVG NUMBER(15,2), 
	CPUUTILMAX1MINDEVICEAVG NUMBER(15,2), 
	CPUUTILAVG1MINDEVICEAVG NUMBER(15,2), 
	USEDBYTESDEVICEAVG NUMBER, 
	FREEBYTESDEVICEAVG NUMBER, 
	AVGUTILDEVICEAVG NUMBER, 
	MAXUTILDEVICEAVG NUMBER
   )  NOCOMPRESS NOLOGGING
  PARTITION BY RANGE (FECHA)
  (
  PARTITION CPUMEMDEVICEAVGHOUR201610 VALUES LESS THAN (TO_DATE('2016.11.01','YYYY.MM.DD')) TABLESPACE TBS_HOUR PCTFREE 10 PCTUSED 80,
  PARTITION CPUMEMDEVICEAVGHOUR201611 VALUES LESS THAN (TO_DATE('2016.12.01','YYYY.MM.DD')) TABLESPACE TBS_HOUR PCTFREE 10 PCTUSED 80,
  PARTITION CPUMEMDEVICEAVGHOUR201612 VALUES LESS THAN (TO_DATE('2017.01.01','YYYY.MM.DD')) TABLESPACE TBS_HOUR PCTFREE 10 PCTUSED 80
  )
  TABLESPACE TBS_HOUR ;

   COMMENT ON COLUMN CSCO_CPU_MEM_DEVICE_AVG_HOUR.FECHA IS 'Reemplazo de la columna TIMESTAMP por ser palabra reservada';
   COMMENT ON TABLE CSCO_CPU_MEM_DEVICE_AVG_HOUR  IS 'Contiene los datos de la union de las tablas CSCO_CPU_DEVICE_AVG y CSCO_MEMORY_DEVICE_AVG unidos por FECHA, NODE';
--------------------------------------------------------
--  DDL for Index PK_CSCO_CPU_MEM_DEVICE_AVG_H
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_CSCO_CPU_MEM_DEVICE_AVG_H ON CSCO_CPU_MEM_DEVICE_AVG_HOUR (FECHA, NODE) LOCAL
  TABLESPACE TBS_HOUR ;
--------------------------------------------------------
--  Constraints for Table CSCO_CPU_MEM_DEVICE_AVG_HOUR
--------------------------------------------------------

  ALTER TABLE CSCO_CPU_MEM_DEVICE_AVG_HOUR ADD CONSTRAINT PK_CSCO_CPU_MEM_DEVICE_AVG_H PRIMARY KEY (FECHA, NODE)  ENABLE;
  ALTER TABLE CSCO_CPU_MEM_DEVICE_AVG_HOUR MODIFY (MAXUTILDEVICEAVG NOT NULL ENABLE);
  ALTER TABLE CSCO_CPU_MEM_DEVICE_AVG_HOUR MODIFY (AVGUTILDEVICEAVG NOT NULL ENABLE);
  ALTER TABLE CSCO_CPU_MEM_DEVICE_AVG_HOUR MODIFY (FREEBYTESDEVICEAVG NOT NULL ENABLE);
  ALTER TABLE CSCO_CPU_MEM_DEVICE_AVG_HOUR MODIFY (USEDBYTESDEVICEAVG NOT NULL ENABLE);
  ALTER TABLE CSCO_CPU_MEM_DEVICE_AVG_HOUR MODIFY (CPUUTILAVG1MINDEVICEAVG NOT NULL ENABLE);
  ALTER TABLE CSCO_CPU_MEM_DEVICE_AVG_HOUR MODIFY (CPUUTILMAX1MINDEVICEAVG NOT NULL ENABLE);
  ALTER TABLE CSCO_CPU_MEM_DEVICE_AVG_HOUR MODIFY (CPUUTILAVG5MINDEVICEAVG NOT NULL ENABLE);
  ALTER TABLE CSCO_CPU_MEM_DEVICE_AVG_HOUR MODIFY (CPUUTILMAX5MINDEVICEAVG NOT NULL ENABLE);
  ALTER TABLE CSCO_CPU_MEM_DEVICE_AVG_HOUR MODIFY (NODE NOT NULL ENABLE);
  ALTER TABLE CSCO_CPU_MEM_DEVICE_AVG_HOUR MODIFY (FECHA NOT NULL ENABLE);
