--------------------------------------------------------
--  DDL for Table CSCO_CGN_STATS_BH
--------------------------------------------------------

  CREATE TABLE CSCO_CGN_STATS_BH 
   (	FECHA DATE, 
	NODE VARCHAR2(255 CHAR), 
	CGNINSTANCEID VARCHAR2(10 CHAR), 
	ACTIVETRANSLATIONS NUMBER(15,2), 
	CREATERATE NUMBER(15,2), 
	DELETERATE NUMBER(15,2), 
	OUTSIDEFORWARDRATE NUMBER(15,2), 
	INSIDEFORWARDRATE NUMBER(15,2), 
	DROPSPORTLIMITEXCEEDED NUMBER(15,2), 
	DROPSSYSTEMLIMITREACHED NUMBER(15,2), 
	DROPSRESOURCEDEPLETION NUMBER(15,2), 
	NOTRANSLATIONENTRYDROPS NUMBER(15,2), 
	ADDRESSTOTALLYFREE NUMBER(15,2), 
	ADDRESSUSED NUMBER(15,2), 
	NUMBEROFSUBSCRIBERS NUMBER(15,2)
   ) NOCOMPRESS NOLOGGING
  TABLESPACE TBS_DAY ;

   COMMENT ON COLUMN CSCO_CGN_STATS_BH.FECHA IS 'Reemplazo de la columna TIMESTAMP por ser palabra reservada';
--------------------------------------------------------
--  DDL for Index CSCO_CGN_STATS_BH_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX CSCO_CGN_STATS_BH_PK ON CSCO_CGN_STATS_BH (FECHA, NODE, CGNINSTANCEID) 
  TABLESPACE TBS_DAY ;
--------------------------------------------------------
--  Constraints for Table CSCO_CGN_STATS_BH
--------------------------------------------------------

  ALTER TABLE CSCO_CGN_STATS_BH ADD CONSTRAINT CSCO_CGN_STATS_BH_PK PRIMARY KEY (FECHA, NODE, CGNINSTANCEID)  ENABLE;
  ALTER TABLE CSCO_CGN_STATS_BH MODIFY (NUMBEROFSUBSCRIBERS NOT NULL ENABLE);
  ALTER TABLE CSCO_CGN_STATS_BH MODIFY (ADDRESSUSED NOT NULL ENABLE);
  ALTER TABLE CSCO_CGN_STATS_BH MODIFY (ADDRESSTOTALLYFREE NOT NULL ENABLE);
  ALTER TABLE CSCO_CGN_STATS_BH MODIFY (NOTRANSLATIONENTRYDROPS NOT NULL ENABLE);
  ALTER TABLE CSCO_CGN_STATS_BH MODIFY (DROPSRESOURCEDEPLETION NOT NULL ENABLE);
  ALTER TABLE CSCO_CGN_STATS_BH MODIFY (DROPSSYSTEMLIMITREACHED NOT NULL ENABLE);
  ALTER TABLE CSCO_CGN_STATS_BH MODIFY (DROPSPORTLIMITEXCEEDED NOT NULL ENABLE);
  ALTER TABLE CSCO_CGN_STATS_BH MODIFY (INSIDEFORWARDRATE NOT NULL ENABLE);
  ALTER TABLE CSCO_CGN_STATS_BH MODIFY (OUTSIDEFORWARDRATE NOT NULL ENABLE);
  ALTER TABLE CSCO_CGN_STATS_BH MODIFY (DELETERATE NOT NULL ENABLE);
  ALTER TABLE CSCO_CGN_STATS_BH MODIFY (CREATERATE NOT NULL ENABLE);
  ALTER TABLE CSCO_CGN_STATS_BH MODIFY (ACTIVETRANSLATIONS NOT NULL ENABLE);
  ALTER TABLE CSCO_CGN_STATS_BH MODIFY (CGNINSTANCEID NOT NULL ENABLE);
  ALTER TABLE CSCO_CGN_STATS_BH MODIFY (NODE NOT NULL ENABLE);
  ALTER TABLE CSCO_CGN_STATS_BH MODIFY (FECHA NOT NULL ENABLE);
