--------------------------------------------------------
--  DDL for Table CSCO_DEVICE_LINKS
--------------------------------------------------------

  CREATE TABLE CSCO_DEVICE_LINKS 
   (	CONTEXTO VARCHAR2(255 CHAR), 
	SEVERITY VARCHAR2(255 CHAR), 
	AENDPOINT VARCHAR2(255 CHAR), 
	PORTNUMBERA VARCHAR2(255 CHAR), 
	BIDIRECTIONAL CHAR(2 BYTE), 
	ZENDPOINT VARCHAR2(255 CHAR), 
	PORTNUMBERZ VARCHAR2(255 CHAR), 
	LINKTYPE CHAR(2 BYTE), 
	ROWNUMBER NUMBER, 
	ELEMENT_ALIASES VARCHAR2(2040 CHAR) GENERATED ALWAYS AS (AENDPOINT||'_'||PORTNUMBERA||'_to_'||ZENDPOINT||'_'||PORTNUMBERZ) VIRTUAL 
   ) 
 NOCOMPRESS NOLOGGING
  TABLESPACE TBS_AUXILIAR ;
--------------------------------------------------------
--  Constraints for Table CSCO_DEVICE_LINKS
--------------------------------------------------------

  ALTER TABLE CSCO_DEVICE_LINKS MODIFY (ROWNUMBER NOT NULL ENABLE);
  ALTER TABLE CSCO_DEVICE_LINKS MODIFY (PORTNUMBERZ NOT NULL ENABLE);
  ALTER TABLE CSCO_DEVICE_LINKS MODIFY (ZENDPOINT NOT NULL ENABLE);
  ALTER TABLE CSCO_DEVICE_LINKS MODIFY (PORTNUMBERA NOT NULL ENABLE);
  ALTER TABLE CSCO_DEVICE_LINKS MODIFY (AENDPOINT NOT NULL ENABLE);
