--------------------------------------------------------
--  DDL for Table EHEALTH_OBJECTS
--------------------------------------------------------

  CREATE TABLE EHEALTH_OBJECTS
   (	ELEMENT_ID NUMBER, 
	ELEMENT_ALIASES VARCHAR2(500 CHAR), 
	VALID_START_DATE DATE, 
	VALID_FINISH_DATE DATE, 
	TIPO VARCHAR2(40 CHAR), 
	ORIGEN VARCHAR2(40 CHAR), 
	DESTINO VARCHAR2(40 CHAR), 
	FLAG_ENABLED CHAR(1 CHAR), 
	GRUPO VARCHAR2(50 CHAR), 
	PAIS VARCHAR2(20 CHAR), 
	ELEMENT_TYPE VARCHAR2(20 CHAR), 
	ELEMENT_NAME VARCHAR2(20 CHAR), 
	INTERFACE_NAME VARCHAR2(100 CHAR), 
	GROUP_TYPE VARCHAR2(20 CHAR), 
	ELEMENT_IP VARCHAR2(15 CHAR), 
	NOMBRE_GRUPO VARCHAR2(50 CHAR), 
	FRONTERA VARCHAR2(30 CHAR), 
	--INTERFACE_NAME_NEW VARCHAR2(100 BYTE), 
	SPEED_MODIFY NUMBER 
	--ELEMENT_ALIASES_NEW VARCHAR2(500 BYTE)
   ) NOCOMPRESS NOLOGGING
  TABLESPACE TBS_AUXILIAR ;
--------------------------------------------------------
--  DDL for Index EHEALTH_OBJECTS_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX EHEALTH_OBJECTS_UK1 ON EHEALTH_OBJECTS (ELEMENT_ALIASES) 
  TABLESPACE TBS_AUXILIAR ;
--------------------------------------------------------
--  Constraints for Table EHEALTH_OBJECTS
--------------------------------------------------------

  ALTER TABLE EHEALTH_OBJECTS ADD CONSTRAINT EHEALTH_OBJECTS_UK1 UNIQUE (ELEMENT_ALIASES)  ENABLE;
  ALTER TABLE EHEALTH_OBJECTS MODIFY (ELEMENT_ALIASES NOT NULL ENABLE);
  ALTER TABLE EHEALTH_OBJECTS MODIFY (ELEMENT_ID NOT NULL ENABLE);
