--------------------------------------------------------
--  DDL for Table EHEALTH_STAT_IP_HOUR
--------------------------------------------------------

  CREATE TABLE EHEALTH_STAT_IP_HOUR 
   (	FECHA DATE, 
	ELEMENT_ID NUMBER, 
	RECEIVEBYTES NUMBER, 
	SENDBYTES NUMBER, 
	IFSPEED NUMBER, 
	RECEIVEDISCARDS NUMBER, 
	SENDDISCARDS NUMBER, 
	RECEIVEERRORS NUMBER(24,2), 
	SENDERRORS NUMBER(24,2), 
	RECEIVETOTALPKTRATE NUMBER(24,2), 
	SENDTOTALPKTRATE NUMBER(24,2), 
	INQUEUEDROPS NUMBER, 
	OUTQUEUEDROPS NUMBER, 
	UPPERCENT NUMBER(10,2), 
	SENDUTIL NUMBER(24,2), 
	SENDTOTALPKTS NUMBER, 
	SENDUCASTPKTPERCENT NUMBER(24,2), 
	SENDMCASTPKTPERCENT NUMBER(24,2), 
	SENDBCASTPKTPERCENT NUMBER(24,2), 
	SENDERRORPERCENT NUMBER(24,2), 
	SENDDISCARDPERCENT NUMBER(24,2), 
	RECEIVEUTIL NUMBER(24,2), 
	RECEIVETOTALPKTS NUMBER(24,2), 
	RECEIVEUCASTPKTPERCENT NUMBER(24,2), 
	RECEIVEMCASTPKTPERCENT NUMBER(24,2), 
	RECEIVEBCASTPKTPERCENT NUMBER(24,2), 
	RECEIVEERRORPERCENT NUMBER(24,2), 
	RECEIVEDISCARDPERCENT NUMBER(24,2), 
	SENDBCASTPKTRATE NUMBER(24,2), 
	RECEIVEBCASTPKTRATE NUMBER(24,2)
   ) NOCOMPRESS NOLOGGING
  PARTITION BY RANGE (FECHA)
  (
    PARTITION STATIPHOUR20161001 VALUES LESS THAN (TO_DATE('2016.11.01','YYYY.MM.DD')) TABLESPACE TBS_HOUR PCTFREE 10 PCTUSED 80,
    PARTITION STATIPHOUR20161101 VALUES LESS THAN (TO_DATE('2016.12.01','YYYY.MM.DD')) TABLESPACE TBS_HOUR PCTFREE 10 PCTUSED 80,
    PARTITION STATIPHOUR20161201 VALUES LESS THAN (TO_DATE('2017.01.01','YYYY.MM.DD')) TABLESPACE TBS_HOUR PCTFREE 10 PCTUSED 80
  )
  TABLESPACE TBS_HOUR ;
--------------------------------------------------------
--  DDL for Index EHEALTH_STAT_IP_HOUR_INDEX1
--------------------------------------------------------

  CREATE INDEX EHEALTH_STAT_IP_HOUR_INDEX1 ON EHEALTH_STAT_IP_HOUR (FECHA DESC, ELEMENT_ID) LOCAL
  TABLESPACE TBS_HOUR ;
--------------------------------------------------------
--  DDL for Index EHEALTH_STAT_IP_HOUR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX EHEALTH_STAT_IP_HOUR_PK ON EHEALTH_STAT_IP_HOUR (FECHA, ELEMENT_ID) 
  TABLESPACE TBS_HOUR ;
--------------------------------------------------------
--  Constraints for Table EHEALTH_STAT_IP_HOUR
--------------------------------------------------------

  ALTER TABLE EHEALTH_STAT_IP_HOUR ADD CONSTRAINT EHEALTH_STAT_IP_HOUR_PK PRIMARY KEY (FECHA, ELEMENT_ID) ENABLE;
  ALTER TABLE EHEALTH_STAT_IP_HOUR MODIFY (RECEIVEBYTES NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_HOUR MODIFY (ELEMENT_ID NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_HOUR MODIFY (RECEIVEBCASTPKTRATE NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_HOUR MODIFY (SENDBCASTPKTRATE NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_HOUR MODIFY (RECEIVEDISCARDPERCENT NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_HOUR MODIFY (RECEIVEERRORPERCENT NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_HOUR MODIFY (RECEIVEBCASTPKTPERCENT NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_HOUR MODIFY (RECEIVEMCASTPKTPERCENT NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_HOUR MODIFY (RECEIVEUCASTPKTPERCENT NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_HOUR MODIFY (RECEIVETOTALPKTS NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_HOUR MODIFY (RECEIVEUTIL NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_HOUR MODIFY (SENDDISCARDPERCENT NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_HOUR MODIFY (SENDERRORPERCENT NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_HOUR MODIFY (SENDBCASTPKTPERCENT NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_HOUR MODIFY (SENDMCASTPKTPERCENT NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_HOUR MODIFY (SENDUCASTPKTPERCENT NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_HOUR MODIFY (SENDTOTALPKTS NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_HOUR MODIFY (SENDUTIL NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_HOUR MODIFY (UPPERCENT NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_HOUR MODIFY (OUTQUEUEDROPS NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_HOUR MODIFY (INQUEUEDROPS NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_HOUR MODIFY (SENDTOTALPKTRATE NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_HOUR MODIFY (RECEIVETOTALPKTRATE NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_HOUR MODIFY (SENDERRORS NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_HOUR MODIFY (RECEIVEERRORS NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_HOUR MODIFY (FECHA NOT NULL ENABLE);
