--------------------------------------------------------
--  DDL for Table EHEALTH_STAT_IP_DAY
--------------------------------------------------------

  CREATE TABLE EHEALTH_STAT_IP_DAY 
   (	FECHA DATE, 
	ELEMENT_ID NUMBER, 
	RECEIVEBYTES NUMBER, 
	SENDBYTES NUMBER, 
	IFSPEED NUMBER, 
	RECEIVEDISCARDS NUMBER, 
	SENDDISCARDS NUMBER, 
	RECEIVEERRORS NUMBER(24,2), 
	SENDERRORS NUMBER(24,2), 
	RECEIVETOTALPKTRATE NUMBER(24,2), 
	SENDTOTALPKTRATE NUMBER(24,2), 
	INQUEUEDROPS NUMBER, 
	OUTQUEUEDROPS NUMBER, 
	UPPERCENT NUMBER(10,2), 
	SENDUTIL NUMBER(24,2), 
	SENDTOTALPKTS NUMBER, 
	SENDUCASTPKTPERCENT NUMBER(24,2), 
	SENDMCASTPKTPERCENT NUMBER(24,2), 
	SENDBCASTPKTPERCENT NUMBER(24,2), 
	SENDERRORPERCENT NUMBER(24,2), 
	SENDDISCARDPERCENT NUMBER(24,2), 
	RECEIVEUTIL NUMBER(24,2), 
	RECEIVETOTALPKTS NUMBER(24,2), 
	RECEIVEUCASTPKTPERCENT NUMBER(24,2), 
	RECEIVEMCASTPKTPERCENT NUMBER(24,2), 
	RECEIVEBCASTPKTPERCENT NUMBER(24,2), 
	RECEIVEERRORPERCENT NUMBER(24,2), 
	RECEIVEDISCARDPERCENT NUMBER(24,2), 
	SENDBCASTPKTRATE NUMBER(24,2), 
	RECEIVEBCASTPKTRATE NUMBER(24,2)
   ) NOCOMPRESS NOLOGGING
  PARTITION BY RANGE (FECHA)
  (
    PARTITION STATIPDAY201610 VALUES LESS THAN (TO_DATE('01.11.2016','DD.MM.YYYY')) TABLESPACE TBS_DAY PCTFREE 10 PCTUSED 80,
    PARTITION STATIPDAY201611 VALUES LESS THAN (TO_DATE('01.12.2016','DD.MM.YYYY')) TABLESPACE TBS_DAY PCTFREE 10 PCTUSED 80,
    PARTITION STATIPDAY201612 VALUES LESS THAN (TO_DATE('01.01.2017','DD.MM.YYYY')) TABLESPACE TBS_DAY PCTFREE 10 PCTUSED 80
  )
  TABLESPACE TBS_DAY ;
--------------------------------------------------------
--  Constraints for Table EHEALTH_STAT_IP_DAY
--------------------------------------------------------

  ALTER TABLE EHEALTH_STAT_IP_DAY MODIFY (RECEIVEBCASTPKTRATE NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_DAY MODIFY (SENDBCASTPKTRATE NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_DAY MODIFY (RECEIVEDISCARDPERCENT NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_DAY MODIFY (RECEIVEERRORPERCENT NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_DAY MODIFY (RECEIVEBCASTPKTPERCENT NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_DAY MODIFY (RECEIVEMCASTPKTPERCENT NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_DAY MODIFY (RECEIVEUCASTPKTPERCENT NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_DAY MODIFY (RECEIVETOTALPKTS NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_DAY MODIFY (RECEIVEUTIL NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_DAY MODIFY (SENDDISCARDPERCENT NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_DAY MODIFY (SENDERRORPERCENT NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_DAY MODIFY (SENDBCASTPKTPERCENT NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_DAY MODIFY (SENDMCASTPKTPERCENT NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_DAY MODIFY (SENDUCASTPKTPERCENT NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_DAY MODIFY (SENDTOTALPKTS NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_DAY MODIFY (SENDUTIL NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_DAY MODIFY (UPPERCENT NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_DAY MODIFY (OUTQUEUEDROPS NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_DAY MODIFY (INQUEUEDROPS NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_DAY MODIFY (SENDTOTALPKTRATE NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_DAY MODIFY (RECEIVETOTALPKTRATE NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_DAY MODIFY (SENDERRORS NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_DAY MODIFY (RECEIVEERRORS NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_DAY MODIFY (SENDDISCARDS NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_DAY MODIFY (RECEIVEDISCARDS NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_DAY MODIFY (IFSPEED NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_DAY MODIFY (SENDBYTES NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_DAY MODIFY (RECEIVEBYTES NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_DAY MODIFY (ELEMENT_ID NOT NULL ENABLE);
  ALTER TABLE EHEALTH_STAT_IP_DAY MODIFY (FECHA NOT NULL ENABLE);
