
select 'create public synonym '||table_name||' for '||owner||'.'||table_name||';'
from all_tables
where owner = 'MCARRASCO'
and table_name like 'CSCO_%';

-- DROP TABLE CGN_STATS_IBHW;

CREATE TABLE CSCO_CGN_STATS_HOUR (
  FECHA                   DATE,
  NODE                    VARCHAR2(255 CHAR),
  CGNINSTANCEID           VARCHAR2(10 CHAR),
  ACTIVETRANSLATIONS      NUMBER(15,2),
  CREATERATE              NUMBER(15,2),
  DELETERATE              NUMBER(15,2),
  OUTSIDEFORWARDRATE      NUMBER(15,2),
  INSIDEFORWARDRATE       NUMBER(15,2),
  DROPSPORTLIMITEXCEEDED  NUMBER(15,2),
  DROPSSYSTEMLIMITREACHED NUMBER(15,2),
  DROPSRESOURCEDEPLETION  NUMBER(15,2),
  NOTRANSLATIONENTRYDROPS NUMBER(15,2),
  ADDRESSTOTALLYFREE      NUMBER(15,2),
  ADDRESSUSED             NUMBER(15,2),
  NUMBEROFSUBSCRIBERS     NUMBER(15,2)
);

COMMENT ON COLUMN CSCO_CGN_STATS_HOUR.FECHA IS 'Reemplazo de la columna TIMESTAMP por ser palabra reservada';

-- DROP TABLE CGN_STATS_DAY;

CREATE TABLE CSCO_CGN_STATS_DAY (
  FECHA                   DATE,
  NODE                    VARCHAR2(255 CHAR),
  CGNINSTANCEID           VARCHAR2(10 CHAR),
  ACTIVETRANSLATIONS      NUMBER(15,2),
  CREATERATE              NUMBER(15,2),
  DELETERATE              NUMBER(15,2),
  OUTSIDEFORWARDRATE      NUMBER(15,2),
  INSIDEFORWARDRATE       NUMBER(15,2),
  DROPSPORTLIMITEXCEEDED  NUMBER(15,2),
  DROPSSYSTEMLIMITREACHED NUMBER(15,2),
  DROPSRESOURCEDEPLETION  NUMBER(15,2),
  NOTRANSLATIONENTRYDROPS NUMBER(15,2),
  ADDRESSTOTALLYFREE      NUMBER(15,2),
  ADDRESSUSED             NUMBER(15,2),
  NUMBEROFSUBSCRIBERS     NUMBER(15,2)
);

COMMENT ON COLUMN CSCO_CGN_STATS_DAY.FECHA IS 'Reemplazo de la columna TIMESTAMP por ser palabra reservada';

-- DROP TABLE CGN_STATS_BH;

CREATE TABLE CSCO_CGN_STATS_BH (
  FECHA                   DATE,
  NODE                    VARCHAR2(255 CHAR),
  CGNINSTANCEID           VARCHAR2(10 CHAR),
  ACTIVETRANSLATIONS      NUMBER(15,2),
  CREATERATE              NUMBER(15,2),
  DELETERATE              NUMBER(15,2),
  OUTSIDEFORWARDRATE      NUMBER(15,2),
  INSIDEFORWARDRATE       NUMBER(15,2),
  DROPSPORTLIMITEXCEEDED  NUMBER(15,2),
  DROPSSYSTEMLIMITREACHED NUMBER(15,2),
  DROPSRESOURCEDEPLETION  NUMBER(15,2),
  NOTRANSLATIONENTRYDROPS NUMBER(15,2),
  ADDRESSTOTALLYFREE      NUMBER(15,2),
  ADDRESSUSED             NUMBER(15,2),
  NUMBEROFSUBSCRIBERS     NUMBER(15,2)
);

COMMENT ON COLUMN CSCO_CGN_STATS_BH.FECHA IS 'Reemplazo de la columna TIMESTAMP por ser palabra reservada';

-- DROP TABLE CGN_STATS_IBHW;

CREATE TABLE CSCO_CGN_STATS_IBHW (
  FECHA                   DATE,
  NODE                    VARCHAR2(255 CHAR),
  CGNINSTANCEID           VARCHAR2(10 CHAR),
  ACTIVETRANSLATIONS      NUMBER(15,2),
  CREATERATE              NUMBER(15,2),
  DELETERATE              NUMBER(15,2),
  OUTSIDEFORWARDRATE      NUMBER(15,2),
  INSIDEFORWARDRATE       NUMBER(15,2),
  DROPSPORTLIMITEXCEEDED  NUMBER(15,2),
  DROPSSYSTEMLIMITREACHED NUMBER(15,2),
  DROPSRESOURCEDEPLETION  NUMBER(15,2),
  NOTRANSLATIONENTRYDROPS NUMBER(15,2),
  ADDRESSTOTALLYFREE      NUMBER(15,2),
  ADDRESSUSED             NUMBER(15,2),
  NUMBEROFSUBSCRIBERS     NUMBER(15,2)
);

COMMENT ON COLUMN CSCO_CGN_STATS_IBHW.FECHA IS 'Reemplazo de la columna TIMESTAMP por ser palabra reservada';

--    PARTITION BY RANGE (TIMESTAMP_) 
--    INTERVAL(NUMTODSINTERVAL (1, 'DAY'))
--   (  
--    PARTITION CGN_STATS_RAW_29042016 VALUES LESS THAN (TO_DATE('29.04.2016','dd.mm.yyyy'))
--   );