
-- DROP TABLE CGN_STATS_RAW;

create table CSCO_CGN_STATS_HOUR(
  FECHA	                  DATE NOT NULL,
  NODE	                  VARCHAR2(255 CHAR) NOT NULL,
  CGNINSTANCEID	          VARCHAR2(10 CHAR) NOT NULL,
  ACTIVETRANSLATIONS	    NUMBER(15,2) NOT NULL,
  CREATERATE	            NUMBER(15,2) NOT NULL,
  DELETERATE	            NUMBER(15,2) NOT NULL,
  OUTSIDEFORWARDRATE	    NUMBER(15,2) NOT NULL,
  INSIDEFORWARDRATE	      NUMBER(15,2) NOT NULL,
  DROPSPORTLIMITEXCEEDED	NUMBER(15,2) NOT NULL,
  DROPSSYSTEMLIMITREACHED	NUMBER(15,2) NOT NULL,
  DROPSRESOURCEDEPLETION	NUMBER(15,2) NOT NULL,
  NOTRANSLATIONENTRYDROPS	NUMBER(15,2) NOT NULL,
  ADDRESSTOTALLYFREE	    NUMBER(15,2) NOT NULL,
  ADDRESSUSED	            NUMBER(15,2) NOT NULL,
  NUMBEROFSUBSCRIBERS	    NUMBER(15,2) NOT NULL
);

-- DROP TABLE CGN_STATS_DAY;

create table CSCO_CGN_STATS_DAY(
  FECHA	                  DATE NOT NULL,
  NODE	                  VARCHAR2(255 CHAR) NOT NULL,
  CGNINSTANCEID	          VARCHAR2(10 CHAR) NOT NULL,
  ACTIVETRANSLATIONS	    NUMBER(15,2) NOT NULL,
  CREATERATE	            NUMBER(15,2) NOT NULL,
  DELETERATE	            NUMBER(15,2) NOT NULL,
  OUTSIDEFORWARDRATE	    NUMBER(15,2) NOT NULL,
  INSIDEFORWARDRATE	      NUMBER(15,2) NOT NULL,
  DROPSPORTLIMITEXCEEDED	NUMBER(15,2) NOT NULL,
  DROPSSYSTEMLIMITREACHED	NUMBER(15,2) NOT NULL,
  DROPSRESOURCEDEPLETION	NUMBER(15,2) NOT NULL,
  NOTRANSLATIONENTRYDROPS	NUMBER(15,2) NOT NULL,
  ADDRESSTOTALLYFREE	    NUMBER(15,2) NOT NULL,
  ADDRESSUSED	            NUMBER(15,2) NOT NULL,
  NUMBEROFSUBSCRIBERS	    NUMBER(15,2) NOT NULL
);

-- DROP TABLE CGN_STATS_BH;

create table CSCO_CGN_STATS_BH(
  FECHA	                  DATE NOT NULL,
  NODE	                  VARCHAR2(255 CHAR) NOT NULL,
  CGNINSTANCEID	          VARCHAR2(10 CHAR) NOT NULL,
  ACTIVETRANSLATIONS	    NUMBER(15,2) NOT NULL,
  CREATERATE	            NUMBER(15,2) NOT NULL,
  DELETERATE	            NUMBER(15,2) NOT NULL,
  OUTSIDEFORWARDRATE	    NUMBER(15,2) NOT NULL,
  INSIDEFORWARDRATE	      NUMBER(15,2) NOT NULL,
  DROPSPORTLIMITEXCEEDED	NUMBER(15,2) NOT NULL,
  DROPSSYSTEMLIMITREACHED	NUMBER(15,2) NOT NULL,
  DROPSRESOURCEDEPLETION	NUMBER(15,2) NOT NULL,
  NOTRANSLATIONENTRYDROPS	NUMBER(15,2) NOT NULL,
  ADDRESSTOTALLYFREE	    NUMBER(15,2) NOT NULL,
  ADDRESSUSED	            NUMBER(15,2) NOT NULL,
  NUMBEROFSUBSCRIBERS	    NUMBER(15,2) NOT NULL
);
