
-- DROP TABLE CPU_DEVICE_AVG_RAW;

CREATE TABLE CSCO_CPU_DEVICE_AVG_HOUR(
FECHA                   DATE NOT NULL,
NODE                    VARCHAR2(255 CHAR) NOT NULL,
CPUUTILMAX5MINDEVICEAVG NUMBER(15,2) NOT NULL,
CPUUTILAVG5MINDEVICEAVG NUMBER(15,2) NOT NULL,
CPUUTILMAX1MINDEVICEAVG NUMBER(15,2) NOT NULL,
CPUUTILAVG1MINDEVICEAVG NUMBER(15,2) NOT NULL
);

-- DROP TABLE CPU_DEVICE_AVG_DAY;

CREATE TABLE CSCO_CPU_DEVICE_AVG_DAY(
FECHA                   DATE NOT NULL,
NODE                    VARCHAR2(255 CHAR) NOT NULL,
CPUUTILMAX5MINDEVICEAVG NUMBER(15,2) NOT NULL,
CPUUTILAVG5MINDEVICEAVG NUMBER(15,2) NOT NULL,
CPUUTILMAX1MINDEVICEAVG NUMBER(15,2) NOT NULL,
CPUUTILAVG1MINDEVICEAVG NUMBER(15,2) NOT NULL
);

-- DROP TABLE CPU_DEVICE_AVG_BH;

CREATE TABLE CSCO_CPU_DEVICE_AVG_BH(
FECHA                   DATE NOT NULL,
NODE                    VARCHAR2(255 CHAR) NOT NULL,
CPUUTILMAX5MINDEVICEAVG NUMBER(15,2) NOT NULL,
CPUUTILAVG5MINDEVICEAVG NUMBER(15,2) NOT NULL,
CPUUTILMAX1MINDEVICEAVG NUMBER(15,2) NOT NULL,
CPUUTILAVG1MINDEVICEAVG NUMBER(15,2) NOT NULL
);

-- DROP TABLE CPU_DEVICE_AVG_IBHW;

CREATE TABLE CSCO_CPU_DEVICE_AVG_IBHW(
FECHA                   DATE NOT NULL,
NODE                    VARCHAR2(255 CHAR) NOT NULL,
CPUUTILMAX5MINDEVICEAVG NUMBER(15,2) NOT NULL,
CPUUTILAVG5MINDEVICEAVG NUMBER(15,2) NOT NULL,
CPUUTILMAX1MINDEVICEAVG NUMBER(15,2) NOT NULL,
CPUUTILAVG1MINDEVICEAVG NUMBER(15,2) NOT NULL
);

--    PARTITION BY RANGE (TIMESTAMP_) 
--    INTERVAL(NUMTODSINTERVAL (1, 'DAY'))
--   (  
--    PARTITION cpu_device_avg_raw_29042016 VALUES LESS THAN (TO_DATE('29.04.2016','dd.mm.yyyy'))
--   );
