
-- DROP TABLE CPU_LOAD_AVG_RAW;

CREATE TABLE CSCO_CPU_LOAD_AVG_HOUR(
FECHA             DATE NOT NULL,
NODE              VARCHAR2(255 CHAR) NOT NULL,
CPULOADID         NUMBER NOT NULL,
CPULOADSAMPLETIME VARCHAR2(10 CHAR) NOT NULL,
CPULOADAVG        NUMBER(10,2) NOT NULL,
CPULOADPEAK       NUMBER(10,2) NOT NULL
);

-- DROP TABLE CPU_LOAD_AVG_DAY;

CREATE TABLE CSCO_CPU_LOAD_AVG_DAY(
FECHA             DATE NOT NULL,
NODE              VARCHAR2(255 CHAR) NOT NULL,
CPULOADID         NUMBER NOT NULL,
CPULOADSAMPLETIME VARCHAR2(10 CHAR) NOT NULL,
CPULOADAVG        NUMBER(10,2) NOT NULL,
CPULOADPEAK       NUMBER(10,2) NOT NULL
);

-- DROP TABLE CPU_LOAD_AVG_BH;

CREATE TABLE CSCO_CPU_LOAD_AVG_BH(
FECHA             DATE NOT NULL,
NODE              VARCHAR2(255 CHAR) NOT NULL,
CPULOADID         NUMBER NOT NULL,
CPULOADSAMPLETIME VARCHAR2(10 CHAR) NOT NULL,
CPULOADAVG        NUMBER(10,2) NOT NULL,
CPULOADPEAK       NUMBER(10,2) NOT NULL
);

-- DROP TABLE CPU_LOAD_AVG_IBHW;

CREATE TABLE CSCO_CPU_LOAD_AVG_IBHW(
FECHA             DATE NOT NULL,
NODE              VARCHAR2(255 CHAR) NOT NULL,
CPULOADID         NUMBER NOT NULL,
CPULOADSAMPLETIME VARCHAR2(10 CHAR) NOT NULL,
CPULOADAVG        NUMBER(10,2) NOT NULL,
CPULOADPEAK       NUMBER(10,2) NOT NULL
);



--    PARTITION BY RANGE (TIMESTAMP_) 
--    INTERVAL(NUMTODSINTERVAL (1, 'DAY'))
--   (  
--    PARTITION CPU_LOAD_AVG_RAW_29042016 VALUES LESS THAN (TO_DATE('29.04.2016','dd.mm.yyyy'))
--   );