 
 -- DROP TABLE CPU_RAW;
 
 CREATE TABLE CSCO_CPU_HOUR(
  FECHA               DATE NOT NULL, 
	NODE                VARCHAR2(16 CHAR) NOT NULL, 
	SLOT                NUMBER NOT NULL, 
	NUMERO              NUMBER NOT NULL, 
	DESCRIPTION         VARCHAR2(255 CHAR) NOT NULL, 
	CPUUTILMAX5MIN      VARCHAR2(255 CHAR) NOT NULL, 
	CPUUTILAVG5MIN      VARCHAR2(20 CHAR) NOT NULL, 
	CPUUTILMAX1MIN      VARCHAR2(20 CHAR) NOT NULL, 
	CPUUTILAVG1MIN      VARCHAR2(20 CHAR) NOT NULL, 
	CPURISINGTHRESHOLD  VARCHAR2(20 CHAR) NOT NULL, 
	CPUFALLINGTHRESHOLD VARCHAR2(20 CHAR) NOT NULL, 
	PROCESSORINDEX      VARCHAR2(20 CHAR) NOT NULL, 
	CPUSLOTSTR          VARCHAR2(9 CHAR) NOT NULL
  );
  
  COMMENT ON COLUMN CSCO_CPU_HOUR.NUMERO IS 'Reemplazo de la columna NUMBER por ser palabra reservada';
  
 CREATE TABLE CSCO_CPU_DAY(
  FECHA               DATE NOT NULL, 
	NODE                VARCHAR2(16 CHAR) NOT NULL, 
	SLOT                NUMBER NOT NULL, 
	NUMERO              NUMBER NOT NULL, 
	DESCRIPTION         VARCHAR2(255 CHAR) NOT NULL, 
	CPUUTILMAX5MIN      VARCHAR2(255 CHAR) NOT NULL, 
	CPUUTILAVG5MIN      VARCHAR2(20 CHAR) NOT NULL, 
	CPUUTILMAX1MIN      VARCHAR2(20 CHAR) NOT NULL, 
	CPUUTILAVG1MIN      VARCHAR2(20 CHAR) NOT NULL, 
	CPURISINGTHRESHOLD  VARCHAR2(20 CHAR) NOT NULL, 
	CPUFALLINGTHRESHOLD VARCHAR2(20 CHAR) NOT NULL, 
	PROCESSORINDEX      VARCHAR2(20 CHAR) NOT NULL, 
	CPUSLOTSTR          VARCHAR2(9 CHAR) NOT NULL
  );
  
  COMMENT ON COLUMN CSCO_CPU_DAY.NUMERO IS 'Reemplazo de la columna NUMBER por ser palabra reservada';
  
 CREATE TABLE CSCO_CPU_BH(
  FECHA               DATE NOT NULL, 
	NODE                VARCHAR2(16 CHAR) NOT NULL, 
	SLOT                NUMBER NOT NULL, 
	NUMERO              NUMBER NOT NULL, 
	DESCRIPTION         VARCHAR2(255 CHAR) NOT NULL, 
	CPUUTILMAX5MIN      VARCHAR2(255 CHAR) NOT NULL, 
	CPUUTILAVG5MIN      VARCHAR2(20 CHAR) NOT NULL, 
	CPUUTILMAX1MIN      VARCHAR2(20 CHAR) NOT NULL, 
	CPUUTILAVG1MIN      VARCHAR2(20 CHAR) NOT NULL, 
	CPURISINGTHRESHOLD  VARCHAR2(20 CHAR) NOT NULL, 
	CPUFALLINGTHRESHOLD VARCHAR2(20 CHAR) NOT NULL, 
	PROCESSORINDEX      VARCHAR2(20 CHAR) NOT NULL, 
	CPUSLOTSTR          VARCHAR2(9 CHAR) NOT NULL
  );
  
  COMMENT ON COLUMN CSCO_CPU_DAY.NUMERO IS 'Reemplazo de la columna NUMBER por ser palabra reservada';
  
 CREATE TABLE CSCO_CPU_IBHW(
  FECHA               DATE NOT NULL, 
	NODE                VARCHAR2(16 CHAR) NOT NULL, 
	SLOT                NUMBER NOT NULL, 
	NUMERO              NUMBER NOT NULL, 
	DESCRIPTION         VARCHAR2(255 CHAR) NOT NULL, 
	CPUUTILMAX5MIN      VARCHAR2(255 CHAR) NOT NULL, 
	CPUUTILAVG5MIN      VARCHAR2(20 CHAR) NOT NULL, 
	CPUUTILMAX1MIN      VARCHAR2(20 CHAR) NOT NULL, 
	CPUUTILAVG1MIN      VARCHAR2(20 CHAR) NOT NULL, 
	CPURISINGTHRESHOLD  VARCHAR2(20 CHAR) NOT NULL, 
	CPUFALLINGTHRESHOLD VARCHAR2(20 CHAR) NOT NULL, 
	PROCESSORINDEX      VARCHAR2(20 CHAR) NOT NULL, 
	CPUSLOTSTR          VARCHAR2(9 CHAR) NOT NULL
  );
  
  COMMENT ON COLUMN CSCO_CPU_IBHW.NUMERO IS 'Reemplazo de la columna NUMBER por ser palabra reservada';
  
--   )
--    PARTITION BY RANGE (TIMESTAMP_) 
--    INTERVAL(NUMTODSINTERVAL (1, 'DAY'))
--   (  
--    PARTITION CPU_RAW_FIRST VALUES LESS THAN (to_date('07.04.2016','dd.mm.yyyy'))
   
  
