
-- DROP TABLE CSCO_DEVICE_LINKS_AUX

CREATE TABLE CSCO_DEVICE_LINKS_AUX(
LINEA     VARCHAR2(4000 CHAR) NOT NULL ENABLE, 
AENDPOINT VARCHAR2(4000 CHAR) GENERATED ALWAYS AS (substr(REGEXP_SUBSTR(linea,'(Key=[^)]*)',1,1),5)) VIRTUAL,
LINKTYPE 	VARCHAR2(4000 CHAR) GENERATED ALWAYS AS (substr(REGEXP_SUBSTR(LINEA,'(LinkType=[^)]*)',1,1),10)) VIRTUAL,
ZENDPOINT VARCHAR2(4000 CHAR) GENERATED ALWAYS AS (substr(REGEXP_SUBSTR(linea,'(Key=[^)]*)',1,2),5)) VIRTUAL,
ROWNUMBER NUMBER
 ) nologging;

COMMENT ON COLUMN CSCO_DEVICE_LINKS_AUX.LINEA IS 'Linea original del archivo';
COMMENT ON COLUMN CSCO_DEVICE_LINKS_AUX.AENDPOINT IS 'Linea armada a partir de la que viene en el archivo';
COMMENT ON COLUMN CSCO_DEVICE_LINKS_AUX.ZENDPOINT IS 'Linea armada a partir de la que viene en el archivo';
COMMENT ON COLUMN CSCO_DEVICE_LINKS_AUX.ROWNUMBER IS 'Corresponde al numero de fila en la que se ubica en el archivo de origen';

create table CSCO_DEVICE_LINKS(
CONTEXTO	VARCHAR2(255 CHAR),
SEVERITY	VARCHAR2(255 CHAR),
AENDPOINT	VARCHAR2(255 CHAR),
BIDIRECTIONAL	CHAR(2),
ZENDPOINT	VARCHAR2(255 CHAR),
LINKTYPE 	CHAR(2),
ROWNUMBER NUMBER) nologging;

COMMENT ON COLUMN CSCO_DEVICE_LINKS.CONTEXTO IS 'Reescritura de la columna CONTEXT por ser palabra reservada';
COMMENT ON COLUMN CSCO_DEVICE_LINKS.AENDPOINT IS 'Reescritura de la columna A End-Point';
COMMENT ON COLUMN CSCO_DEVICE_LINKS.ZENDPOINT IS 'Reescritura de la columna Z End-Point';
COMMENT ON COLUMN CSCO_DEVICE_LINKS.LINKTYPE IS 'Reescritura de la columna Link Type';
COMMENT ON COLUMN CSCO_DEVICE_LINKS.BIDIRECTIONAL IS 'Reescritura de la columna BI DIRECTIONAL';
COMMENT ON COLUMN CSCO_DEVIVE_LINKS.ROWNUMBER IS 'Corresponde al numero de fila en la que se ubica en el archivo de origen';

--
-- drop table CSCO_INVENTORY_AUX;

create table CSCO_INVENTORY_AUX(
ROWNUMBER      NUMBER NOT NULL,
LINEA         VARCHAR2(4000 CHAR) NOT NULL,
VALOR         VARCHAR2(4000 CHAR) NOT NULL) nologging;
/*,
DEVICE	      VARCHAR2(4000 CHAR) GENERATED ALWAYS AS (substr(REGEXP_SUBSTR(LINEA,'(key=DeviceName, value=[^)]*)',1,1),23)) VIRTUAL,
DEVICE_SERIES	VARCHAR2(4000 CHAR) GENERATED ALWAYS AS (substr(REGEXP_SUBSTR(LINEA,'(key=DeviceSerialNumber, value=[^)]*)',1,1),31)) VIRTUAL,
ELEMENT_TYPE	VARCHAR2(4000 CHAR) GENERATED ALWAYS AS (substr(REGEXP_SUBSTR(LINEA,'(key=ElementType, value=[^)]*)',1,1),24)) VIRTUAL,
IP_ADDRESS	  VARCHAR2(4000 CHAR) GENERATED ALWAYS AS (substr(REGEXP_SUBSTR(LINEA,'(key=IP, value=[^)]*)',1,1),15)) VIRTUAL*/

create table CSCO_INVENTORY(
DEVICE	      VARCHAR2(255 CHAR) ,
DEVICE_SERIES	VARCHAR2(255 CHAR) ,
ELEMENT_TYPE	VARCHAR2(255 CHAR) ,
IP_ADDRESS	  VARCHAR2(255 CHAR) 
) nologging;


COMMENT ON COLUMN CSCO_INVENTORY.IP_ADDRESS IS 'Reescritura de la columna IP ADDRESS por ser palabra reservada';
COMMENT ON COLUMN CSCO_INVENTORY.DEVICE_SERIES IS 'Reescritura de la columna DEVICE SERIES';
COMMENT ON COLUMN CSCO_INVENTORY.ELEMENT_TYPE IS 'Reescritura de la columna ELEMENT TYPE';






