
drop table CSCO_CGN_STATS_HOUR;

CREATE TABLE CSCO_CGN_STATS_HOUR (
  FECHA DATE NOT NULL ENABLE, 
	NODE VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	CGNINSTANCEID VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	ACTIVETRANSLATIONS NUMBER(15,2) NOT NULL ENABLE, 
	CREATERATE NUMBER(15,2) NOT NULL ENABLE, 
	DELETERATE NUMBER(15,2) NOT NULL ENABLE, 
	OUTSIDEFORWARDRATE NUMBER(15,2) NOT NULL ENABLE, 
	INSIDEFORWARDRATE NUMBER(15,2) NOT NULL ENABLE, 
	DROPSPORTLIMITEXCEEDED NUMBER(15,2) NOT NULL ENABLE, 
	DROPSSYSTEMLIMITREACHED NUMBER(15,2) NOT NULL ENABLE, 
	DROPSRESOURCEDEPLETION NUMBER(15,2) NOT NULL ENABLE, 
	NOTRANSLATIONENTRYDROPS NUMBER(15,2) NOT NULL ENABLE, 
	ADDRESSTOTALLYFREE NUMBER(15,2) NOT NULL ENABLE, 
	ADDRESSUSED NUMBER(15,2) NOT NULL ENABLE, 
	NUMBEROFSUBSCRIBERS NUMBER(15,2) NOT NULL ENABLE, 
	 CONSTRAINT CSCO_CGN_STATS_HOUR_PK PRIMARY KEY (FECHA, NODE, CGNINSTANCEID) 
   ) LOGGING
   PARTITION BY RANGE (FECHA) 
   (  
    PARTITION CGNSTATSHOUR2016100200 VALUES LESS THAN (TO_DATE('2016.10.02 01','YYYY.MM.DD HH24')),
    PARTITION CGNSTATSHOUR2016100201 VALUES LESS THAN (TO_DATE('2016.10.02 02','YYYY.MM.DD HH24')),
    PARTITION CGNSTATSHOUR2016100202 VALUES LESS THAN (TO_DATE('2016.10.02 03','YYYY.MM.DD HH24'))
   )
   TABLESPACE TBS_HOUR PCTFREE 10 PCTUSED 80;

   COMMENT ON COLUMN CSCO_CGN_STATS_HOUR.FECHA IS 'Reemplazo de la columna TIMESTAMP por ser palabra reservada';
   
   