
--drop table CSCO_INTERFACE_AVAIL_HOUR;

create table CSCO_INTERFACE_AVAIL_HOUR(
FECHA           DATE NOT NULL,
NODE            VARCHAR2(255 CHAR) NOT NULL,
INTERFACE_DISP  VARCHAR2(255 CHAR) NOT NULL,
IFINDEX         NUMBER NOT NULL,
UPPERCENT       NUMBER(10,2) NOT NULL,
DOWNPERCENT     NUMBER(10,2) NOT NULL,
TIMEOUTPERCENT  NUMBER(10,2) NOT NULL
) nologging;
