
-- DROP TABLE CSCO_DEVICE_LINKS_AUX

CREATE TABLE CSCO_DEVICE_LINKS_AUX(
LINEA     VARCHAR2(4000 CHAR) NOT NULL ENABLE, 
AENDPOINT VARCHAR2(4000 CHAR) GENERATED ALWAYS AS (substr(REGEXP_SUBSTR(linea,'(Key=[^)]*)',1,1),5)) VIRTUAL,
LINKTYPE 	VARCHAR2(4000 CHAR) GENERATED ALWAYS AS (substr(REGEXP_SUBSTR(LINEA,'(LinkType=[^)]*)',1,1),10)) VIRTUAL,
ZENDPOINT VARCHAR2(4000 CHAR) GENERATED ALWAYS AS (substr(REGEXP_SUBSTR(linea,'(Key=[^)]*)',1,2),5)) VIRTUAL,
ROWNUMBER NUMBER
 ) nologging;

COMMENT ON COLUMN CSCO_DEVICE_LINKS_AUX.LINEA IS 'Linea original del archivo';
COMMENT ON COLUMN CSCO_DEVICE_LINKS_AUX.AENDPOINT IS 'Linea armada a partir de la que viene en el archivo';
COMMENT ON COLUMN CSCO_DEVICE_LINKS_AUX.ZENDPOINT IS 'Linea armada a partir de la que viene en el archivo';

create table CSCO_DEVICE_LINKS(
CONTEXTO	VARCHAR2(255 CHAR),
SEVERITY	VARCHAR2(255 CHAR),
AENDPOINT	VARCHAR2(255 CHAR),
BIDIRECTIONAL	CHAR(2),
ZENDPOINT	VARCHAR2(255 CHAR),
LINKTYPE 	CHAR(2)) nologging;

COMMENT ON COLUMN CSCO_DEVICE_LINKS.CONTEXTO IS 'Reescritura de la columna CONTEXT por ser palabra reservada';
COMMENT ON COLUMN CSCO_DEVICE_LINKS.AENDPOINT IS 'Reescritura de la columna A End-Point';
COMMENT ON COLUMN CSCO_DEVICE_LINKS.ZENDPOINT IS 'Reescritura de la columna Z End-Point';
COMMENT ON COLUMN CSCO_DEVICE_LINKS.LINKTYPE IS 'Reescritura de la columna Link Type';
COMMENT ON COLUMN CSCO_DEVICE_LINKS.BIDIRECTIONAL IS 'Reescritura de la columna BI DIRECTIONAL';

create table CSCO_INVENTORY(
DEVICE	      VARCHAR2(255 CHAR),
IP_ADDRESS	  VARCHAR2(255 CHAR),
DEVICE_SERIES	VARCHAR2(255 CHAR),
ELEMENT_TYPE	VARCHAR2(255 CHAR)) nologging;

COMMENT ON COLUMN CSCO_INVENTORY.IP_ADDRESS IS 'Reescritura de la columna IP ADDRESS por ser palabra reservada';
COMMENT ON COLUMN CSCO_INVENTORY.DEVICE_SERIES IS 'Reescritura de la columna DEVICE SERIES';
COMMENT ON COLUMN CSCO_INVENTORY.ELEMENT_TYPE IS 'Reescritura de la columna ELEMENT TYPE';