CREATE TABLE CSCO_INTERFACE_DAY (
FECHA	DATE,
NODE	VARCHAR2(255 CHAR),
INTERFAZ	VARCHAR2(255 CHAR),
IFINDEX	NUMBER,
IFTYPE	NUMBER,
IFSPEED	NUMBER(24,2),
SENDUTIL	NUMBER(24,2),
SENDTOTALPKTS	NUMBER,
SENDTOTALPKTRATE	NUMBER(24,2),
SENDBYTES	NUMBER,
SENDBYTERATE	NUMBER(24,2),
SENDBITRATE	NUMBER(24,2),
SENDUCASTPKTPERCENT	NUMBER(24,2),
SENDMCASTPKTPERCENT	NUMBER(24,2),
SENDBCASTPKTPERCENT	NUMBER(24,2),
SENDERRORS	NUMBER(24,2),
SENDERRORPERCENT	NUMBER(24,2),
SENDDISCARDS	NUMBER(24,2),
SENDDISCARDPERCENT	NUMBER(24,2),
RECEIVEUTIL	NUMBER(24,2),
RECEIVETOTALPKTS	NUMBER(24,2),
RECEIVETOTALPKTRATE	NUMBER(24,2),
RECEIVEBYTES	NUMBER(24,2),
RECEIVEBYTERATE	NUMBER(24,2),
RECEIVEBITRATE	NUMBER(24,2),
RECEIVEUCASTPKTPERCENT	NUMBER(24,2),
RECEIVEMCASTPKTPERCENT	NUMBER(24,2),
RECEIVEBCASTPKTPERCENT	NUMBER(24,2),
RECEIVEERRORS	NUMBER(24,2),
RECEIVEERRORPERCENT	NUMBER(24,2),
RECEIVEDISCARDS	NUMBER(24,2),
RECEIVEDISCARDPERCENT	NUMBER(24,2),
SENDBCASTPKTRATE	NUMBER(24,2),
RECEIVEBCASTPKTRATE	NUMBER(24,2),
IFTYPESTRING	VARCHAR2(255 CHAR)
)
NOCOMPRESS
NOLOGGING
PARTITION BY RANGE (FECHA)
INTERVAL(NUMTODSINTERVAL(1, 'DAY'))
(
  PARTITION INTERFACEDAY_FIRST VALUES LESS THAN (TO_DATE('30.12.2016','DD.MM.YYYY'))
)
TABLESPACE DEVELOPER;

CREATE INDEX IDX_INTERFACE_DAY_FNI ON CSCO_INTERFACE_DAY (FECHA,NODE,INTERFAZ) LOCAL;

INSERT INTO CSCO_INTERFACE_DAY
SELECT  TRUNC(FECHA)                          FECHA,
        NODE,
        INTERFAZ,
        SUM(0)                                IFINDEX,
        SUM(0)                                IFTYPE,
        SUM(0)                                IFSPEED,
        ROUND(SUM(SENDUTIL),2)                SENDUTIL,
        ROUND(SUM(SENDTOTALPKTS),2)           SENDTOTALPKTS,
        ROUND(AVG(SENDTOTALPKTRATE),2)        SENDTOTALPKTRATE,
        ROUND(SUM(SENDBYTES),2)               SENDBYTES,
        ROUND(AVG(SENDBYTERATE),2)            SENDBYTERATE,
        ROUND(AVG(SENDBITRATE),2)             SENDBITRATE,
        ROUND(AVG(SENDUCASTPKTPERCENT),2)     SENDUCASTPKTPERCENT,
        ROUND(AVG(SENDMCASTPKTPERCENT),2)     SENDMCASTPKTPERCENT,
        ROUND(AVG(SENDBCASTPKTPERCENT),2)     SENDBCASTPKTPERCENT,
        ROUND(SUM(SENDERRORS),2)              SENDERRORS,
        ROUND(AVG(SENDERRORPERCENT),2)        SENDERRORPERCENT,
        ROUND(SUM(SENDDISCARDS),2)            SENDDISCARDS,
        ROUND(AVG(SENDDISCARDPERCENT),2)      SENDDISCARDPERCENT,
        ROUND(SUM(RECEIVEUTIL),2)             RECEIVEUTIL,
        ROUND(SUM(RECEIVETOTALPKTS),2)        RECEIVETOTALPKTS,
        ROUND(AVG(RECEIVETOTALPKTRATE),2)     RECEIVETOTALPKTRATE,
        ROUND(SUM(RECEIVEBYTES),2)            RECEIVEBYTES,
        ROUND(AVG(RECEIVEBYTERATE),2)         RECEIVEBYTERATE,
        ROUND(AVG(RECEIVEBITRATE),2)          RECEIVEBITRATE,
        ROUND(AVG(RECEIVEUCASTPKTPERCENT),2)  RECEIVEUCASTPKTPERCENT,
        ROUND(AVG(RECEIVEMCASTPKTPERCENT),2)  RECEIVEMCASTPKTPERCENT,
        ROUND(AVG(RECEIVEBCASTPKTPERCENT),2)  RECEIVEBCASTPKTPERCENT,
        ROUND(SUM(RECEIVEERRORS),2)           RECEIVEERRORS,
        ROUND(AVG(RECEIVEERRORPERCENT),2)     RECEIVEERRORPERCENT,
        ROUND(SUM(RECEIVEDISCARDS),2)         RECEIVEDISCARDS,
        ROUND(AVG(RECEIVEDISCARDPERCENT),2)   RECEIVEDISCARDPERCENT,
        ROUND(AVG(SENDBCASTPKTRATE),2)        SENDBCASTPKTRATE,
        ROUND(AVG(RECEIVEBCASTPKTRATE),2)     RECEIVEBCASTPKTRATE,
        IFTYPESTRING
FROM CSCO_INTERFACE_HOUR 
--WHERE TRUNC(FECHA) = '30.12.2016'
--AND NODE ='CRR-PE-R02'
--AND INTERFAZ = 'GigabitEthernet2/40'
GROUP BY TRUNC(FECHA),
        NODE,
        INTERFAZ,
--        IFINDEX,
--        IFTYPE,
--        IFSPEED,
        IFTYPESTRING;
        
WITH  CIH AS (SELECT  TRUNC(FECHA)                          FECHA,
                      NODE,
                      INTERFAZ,
                      IFINDEX,
                      IFTYPE,
                      LAST_VALUE(IFSPEED)-- IGNORE NULLS
                                    OVER (PARTITION BY  TO_CHAR(FECHA,'DD.MM.YYYY'),
                                                              NODE,
                                                              INTERFAZ,
                                                              IFINDEX,
                                                              IFTYPE,
                                                              IFTYPESTRING
                                                ORDER BY  TO_CHAR(FECHA,'DD.MM.YYYY HH24') RANGE
                                                BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
                                                              ) IFSPEED,
                      SENDUTIL,
                      SENDTOTALPKTS,
                      SENDTOTALPKTRATE,
                      SENDBYTES,
                      SENDBYTERATE,
                      SENDBITRATE,
                      SENDUCASTPKTPERCENT,
                      SENDMCASTPKTPERCENT,
                      SENDBCASTPKTPERCENT,
                      SENDERRORS,
                      SENDERRORPERCENT,
                      SENDDISCARDS,
                      SENDDISCARDPERCENT,
                      RECEIVEUTIL,
                      RECEIVETOTALPKTS,
                      RECEIVETOTALPKTRATE,
                      RECEIVEBYTES,
                      RECEIVEBYTERATE,
                      RECEIVEBITRATE,
                      RECEIVEUCASTPKTPERCENT,
                      RECEIVEMCASTPKTPERCENT,
                      RECEIVEBCASTPKTPERCENT,
                      RECEIVEERRORS,
                      RECEIVEERRORPERCENT,
                      RECEIVEDISCARDS,
                      RECEIVEDISCARDPERCENT,
                      SENDBCASTPKTRATE,
                      RECEIVEBCASTPKTRATE,
                      IFTYPESTRING
              FROM CSCO_INTERFACE_HOUR
              WHERE TRUNC(FECHA) BETWEEN TO_DATE('30.12.2016','DD.MM.YYYY') AND TO_DATE('30.12.2016','DD.MM.YYYY') + 86399/86400
              AND NODE ='CRR-PE-R02'
              AND INTERFAZ = 'GigabitEthernet2/40')    
SELECT  TRUNC(FECHA)                          FECHA,
        NODE,
        INTERFAZ,
        IFINDEX,
        IFTYPE,
        MAX(IFSPEED) IFSPEED,
        ROUND(AVG(SENDUTIL),2)                SENDUTIL,
        ROUND(SUM(SENDTOTALPKTS),2)           SENDTOTALPKTS,
        ROUND(AVG(SENDTOTALPKTRATE),2)        SENDTOTALPKTRATE,
        ROUND(SUM(SENDBYTES),2)               SENDBYTES,
        ROUND(AVG(SENDBYTERATE),2)            SENDBYTERATE,
        ROUND(AVG(SENDBITRATE),2)             SENDBITRATE,
        ROUND(AVG(SENDUCASTPKTPERCENT),2)     SENDUCASTPKTPERCENT,
        ROUND(AVG(SENDMCASTPKTPERCENT),2)     SENDMCASTPKTPERCENT,
        ROUND(AVG(SENDBCASTPKTPERCENT),2)     SENDBCASTPKTPERCENT,
        ROUND(SUM(SENDERRORS),2)              SENDERRORS,
        ROUND(AVG(SENDERRORPERCENT),2)        SENDERRORPERCENT,
        ROUND(SUM(SENDDISCARDS),2)            SENDDISCARDS,
        ROUND(AVG(SENDDISCARDPERCENT),2)      SENDDISCARDPERCENT,
        ROUND(AVG(RECEIVEUTIL),2)             RECEIVEUTIL,
        ROUND(SUM(RECEIVETOTALPKTS),2)        RECEIVETOTALPKTS,
        ROUND(AVG(RECEIVETOTALPKTRATE),2)     RECEIVETOTALPKTRATE,
        ROUND(SUM(RECEIVEBYTES),2)            RECEIVEBYTES,
        ROUND(AVG(RECEIVEBYTERATE),2)         RECEIVEBYTERATE,
        ROUND(AVG(RECEIVEBITRATE),2)          RECEIVEBITRATE,
        ROUND(AVG(RECEIVEUCASTPKTPERCENT),2)  RECEIVEUCASTPKTPERCENT,
        ROUND(AVG(RECEIVEMCASTPKTPERCENT),2)  RECEIVEMCASTPKTPERCENT,
        ROUND(AVG(RECEIVEBCASTPKTPERCENT),2)  RECEIVEBCASTPKTPERCENT,
        ROUND(SUM(RECEIVEERRORS),2)           RECEIVEERRORS,
        ROUND(AVG(RECEIVEERRORPERCENT),2)     RECEIVEERRORPERCENT,
        ROUND(SUM(RECEIVEDISCARDS),2)         RECEIVEDISCARDS,
        ROUND(AVG(RECEIVEDISCARDPERCENT),2)   RECEIVEDISCARDPERCENT,
        ROUND(AVG(SENDBCASTPKTRATE),2)        SENDBCASTPKTRATE,
        ROUND(AVG(RECEIVEBCASTPKTRATE),2)     RECEIVEBCASTPKTRATE,
        IFTYPESTRING
FROM CIH--CSCO_INTERFACE_HOUR
WHERE TRUNC(FECHA) BETWEEN TO_DATE('30.12.2016','DD.MM.YYYY') AND TO_DATE('30.12.2016','DD.MM.YYYY') + 86399/86400
AND NODE ='CRR-PE-R02'
AND INTERFAZ = 'GigabitEthernet2/40'
GROUP BY TRUNC(FECHA),
        NODE,
        INTERFAZ,
        IFINDEX,
        IFTYPE,
        IFTYPESTRING;        