-- DROP TABLE CSCO_LINKS PURGE;

CREATE TABLE CSCO_LINKS (
  ELEMENT_ID        NUMBER, 
  ELEMENT_ALIASES   VARCHAR2(500 CHAR) , 
  VALID_START_DATE  DATE, 
  VALID_FINISH_DATE DATE, 
  TIPO              VARCHAR2(40 CHAR),
  EQUIPO_A	        VARCHAR2(255 CHAR),
  INTERFACE_A	      VARCHAR2(255 CHAR),
  EQUIPO_B	        VARCHAR2(255 CHAR),
  INTERFACE_B	      VARCHAR2(255 CHAR),
  ORIGEN            VARCHAR2(40 CHAR), 
  DESTINO           VARCHAR2(40 CHAR), 
  FLAG_ENABLED      CHAR(1 CHAR), 
  GRUPO             VARCHAR2(50 CHAR), 
  PAIS              VARCHAR2(20 CHAR), 
  ELEMENT_TYPE      VARCHAR2(20 CHAR), 
  ELEMENT_NAME      VARCHAR2(20 CHAR), 
  INTERFACE_NAME    VARCHAR2(100 CHAR), 
  GROUP_TYPE        VARCHAR2(20 CHAR), 
  ELEMENT_IP        VARCHAR2(15 CHAR), 
  NOMBRE_GRUPO      VARCHAR2(50 CHAR), 
  FRONTERA          VARCHAR2(30 CHAR), 
  BORDE             VARCHAR2(50 CHAR),
  SPEED_MODIFY      NUMBER
 ) 
NOCOMPRESS LOGGING 
--TABLESPACE TBS_HOUR 
TABLESPACE DEVELOPER;

COMMENT ON TABLE CSCO_LINKS IS 'Vinculos Cisco Prime';

CREATE PUBLIC SYNONYM CSCO_LINKS FOR MCARRASCO.CSCO_LINKS;

CREATE PUBLIC SYNONYM CSCO_LINKS FOR SMART.CSCO_LINKS;

GRANT SELECT, INSERT, UPDATE ON CSCO_LINKS TO CTI9838;
GRANT SELECT, INSERT, UPDATE ON CSCO_LINKS TO PRFC;
GRANT SELECT, INSERT, UPDATE ON CSCO_LINKS TO EGINER;
