CREATE TABLE CSCO_INTERFACE_HOUR(
FECHA	DATE,
NODE	VARCHAR2(255 CHAR),
INTERFAZ	VARCHAR2(255 CHAR),
IFINDEX	NUMBER,
IFTYPE	NUMBER,
IFSPEED	NUMBER(24,2),
SENDUTIL	NUMBER(24,2),
SENDTOTALPKTS	NUMBER,
SENDTOTALPKTRATE	NUMBER(24,2),
SENDBYTES	NUMBER,
SENDBYTERATE	NUMBER(24,2),
SENDBITRATE	NUMBER(24,2),
SENDUCASTPKTPERCENT	NUMBER(24,2),
SENDMCASTPKTPERCENT	NUMBER(24,2),
SENDBCASTPKTPERCENT	NUMBER(24,2),
SENDERRORS	NUMBER(24,2),
SENDERRORPERCENT	NUMBER(24,2),
SENDDISCARDS	NUMBER(24,2),
SENDDISCARDPERCENT	NUMBER(24,2),
RECEIVEUTIL	NUMBER(24,2),
RECEIVETOTALPKTS	NUMBER(24,2),
RECEIVETOTALPKTRATE	NUMBER(24,2),
RECEIVEBYTES	NUMBER(24,2),
RECEIVEBYTERATE	NUMBER(24,2),
RECEIVEBITRATE	NUMBER(24,2),
RECEIVEUCASTPKTPERCENT	NUMBER(24,2),
RECEIVEMCASTPKTPERCENT	NUMBER(24,2),
RECEIVEBCASTPKTPERCENT	NUMBER(24,2),
RECEIVEERRORS	NUMBER(24,2),
RECEIVEERRORPERCENT	NUMBER(24,2),
RECEIVEDISCARDS	NUMBER(24,2),
RECEIVEDISCARDPERCENT	NUMBER(24,2),
SENDBCASTPKTRATE	NUMBER(24,2),
RECEIVEBCASTPKTRATE	NUMBER(24,2),
IFTYPESTRING	VARCHAR2(255 CHAR),
MAX_SEND_RECEIVE	NUMBER GENERATED ALWAYS AS (GREATEST(NVL(SENDBYTES,0),NVL(RECEIVEBYTES,0))) VIRTUAL
)
NOCOMPRESS
NOLOGGING
PARTITION BY RANGE (FECHA)
INTERVAL(NUMTODSINTERVAL(1, 'HOUR'))
(
  PARTITION INTERFACEHOUR_FIRST VALUES LESS THAN (TO_DATE('30.12.2016','DD.MM.YYYY'))
)
TABLESPACE DEVELOPER;

CREATE INDEX IDX_INTERFACE_HOUR_FNI ON CSCO_INTERFACE_HOUR (FECHA,NODE,INTERFAZ) LOCAL;
CREATE INDEX IDX_INTERFACE_HOUR_F ON CSCO_INTERFACE_HOUR (TO_CHAR(FECHA,'DD.MM.YYYY')) LOCAL;

CREATE PUBLIC SYNONYM CSCO_INTERFACE_HOUR FOR MCARRASCO.CSCO_INTERFACE_HOUR;



alter table csco_interface_hour add MAX_SEND_RECEIVE	NUMBER GENERATED ALWAYS AS (GREATEST(NVL(SENDBYTES,0),NVL(RECEIVEBYTES,0))) VIRTUAL;