
-- DROP TABLE CSCO_INTERFACE_IBHW PURGE;

CREATE TABLE CSCO_INTERFACE_IBHW(
FECHA	                  DATE,
NODE	                  VARCHAR2(255 CHAR),
INTERFAZ	              VARCHAR2(255 CHAR),
IFINDEX	                NUMBER,
IFTYPE	                NUMBER,
IFSPEED	                NUMBER(24,2),
SENDUTIL	              NUMBER(24,2),
SENDTOTALPKTS	          NUMBER,
SENDTOTALPKTRATE	      NUMBER(24,2),
SENDBYTES	              NUMBER,
SENDBYTERATE	          NUMBER(24,2),
SENDBITRATE	            NUMBER(24,2),
SENDUCASTPKTPERCENT	    NUMBER(24,2),
SENDMCASTPKTPERCENT	    NUMBER(24,2),
SENDBCASTPKTPERCENT	    NUMBER(24,2),
SENDERRORS	            NUMBER(24,2),
SENDERRORPERCENT	      NUMBER(24,2),
SENDDISCARDS	          NUMBER(24,2),
SENDDISCARDPERCENT	    NUMBER(24,2),
RECEIVEUTIL	            NUMBER(24,2),
RECEIVETOTALPKTS	      NUMBER(24,2),
RECEIVETOTALPKTRATE	    NUMBER(24,2),
RECEIVEBYTES	          NUMBER(24,2),
RECEIVEBYTERATE	        NUMBER(24,2),
RECEIVEBITRATE	        NUMBER(24,2),
RECEIVEUCASTPKTPERCENT	NUMBER(24,2),
RECEIVEMCASTPKTPERCENT	NUMBER(24,2),
RECEIVEBCASTPKTPERCENT	NUMBER(24,2),
RECEIVEERRORS	          NUMBER(24,2),
RECEIVEERRORPERCENT	    NUMBER(24,2),
RECEIVEDISCARDS	        NUMBER(24,2),
RECEIVEDISCARDPERCENT	  NUMBER(24,2),
SENDBCASTPKTRATE	      NUMBER(24,2),
RECEIVEBCASTPKTRATE	    NUMBER(24,2),
IFTYPESTRING	          VARCHAR2(255 CHAR),
MAX_SEND_RECEIVE        NUMBER
)
NOCOMPRESS
NOLOGGING
PARTITION BY RANGE (FECHA)
INTERVAL(NUMTODSINTERVAL(1, 'DAY'))
(
  PARTITION INTERFACEIBHW_FIRST VALUES LESS THAN (TO_DATE('01.10.2016','DD.MM.YYYY'))
)
TABLESPACE TBS_SUMMARY;

CREATE INDEX IDX_INTERFACE_IBHW_FNI ON CSCO_INTERFACE_IBHW (FECHA,NODE,INTERFAZ) LOCAL;
CREATE INDEX IDX_INTERFACE_IBHW_F ON CSCO_INTERFACE_IBHW (TO_CHAR(FECHA,'DD.MM.YYYY')) LOCAL;

CREATE PUBLIC SYNONYM CSCO_INTERFACE_IBHW FOR SMART.CSCO_INTERFACE_IBHW;
---
SELECT  '01.01.2017' FECHA,  
        NODE,    
        INTERFAZ,                      
        IFINDEX,                        
        IFTYPE,
        ROUND(AVG(IFSPEED),2) IFSPEED,                        
        ROUND(AVG(SENDUTIL),2) SENDUTIL,                      
        ROUND(AVG(SENDTOTALPKTS),2) SENDTOTALPKTS,            
        ROUND(AVG(SENDTOTALPKTRATE),2) SENDTOTALPKTRATE,      
        ROUND(AVG(SENDBYTES),2) SENDBYTES,                    
        ROUND(AVG(SENDBYTERATE),2) SENDBYTERATE,              
        ROUND(AVG(SENDBITRATE),2) SENDBITRATE,                
        ROUND(AVG(SENDUCASTPKTPERCENT),2) SENDUCASTPKTPERCENT,
        ROUND(AVG(SENDMCASTPKTPERCENT),2) SENDMCASTPKTPERCENT,
        ROUND(AVG(SENDBCASTPKTPERCENT),2) SENDBCASTPKTPERCENT,
        ROUND(AVG(SENDERRORS),2) SENDERRORS,                  
        ROUND(AVG(SENDERRORPERCENT),2) SENDERRORPERCENT,      
        ROUND(AVG(SENDDISCARDS),2) SENDDISCARDS,              
        ROUND(AVG(SENDDISCARDPERCENT),2) SENDDISCARDPERCENT,  
        ROUND(AVG(RECEIVEUTIL),2) RECEIVEUTIL,                
        ROUND(AVG(RECEIVETOTALPKTS),2) RECEIVETOTALPKTS,      
        ROUND(AVG(RECEIVETOTALPKTRATE),2) RECEIVETOTALPKTRATE,
        ROUND(AVG(RECEIVEBYTES),2) RECEIVEBYTES,              
        ROUND(AVG(RECEIVEBYTERATE),2) RECEIVEBYTERATE,        
        ROUND(AVG(RECEIVEBITRATE),2) RECEIVEBITRATE,          
        ROUND(AVG(RECEIVEUCASTPKTPERCENT),2) RECEIVEUCASTPKTPERCENT,                    
        ROUND(AVG(RECEIVEMCASTPKTPERCENT),2) RECEIVEMCASTPKTPERCENT,                    
        ROUND(AVG(RECEIVEBCASTPKTPERCENT),2) RECEIVEBCASTPKTPERCENT,                    
        ROUND(AVG(RECEIVEERRORS),2) RECEIVEERRORS,            
        ROUND(AVG(RECEIVEERRORPERCENT),2) RECEIVEERRORPERCENT,
        ROUND(AVG(RECEIVEDISCARDS),2) RECEIVEDISCARDS,        
        ROUND(AVG(RECEIVEDISCARDPERCENT),2) RECEIVEDISCARDPERCENT,                      
        ROUND(AVG(SENDBCASTPKTRATE),2) SENDBCASTPKTRATE,      
        ROUND(AVG(RECEIVEBCASTPKTRATE),2) RECEIVEBCASTPKTRATE,
        IFTYPESTRING,
        ROUND(AVG(MAX_SEND_RECEIVE),2) MAX_SEND_RECEIVE

FROM (
      SELECT  TRUNC(FECHA,'DAY') FECHA,NODE,INTERFAZ,IFINDEX,IFTYPE,IFSPEED,SENDUTIL,SENDTOTALPKTS,SENDTOTALPKTRATE,SENDBYTES,
              SENDBYTERATE,SENDBITRATE,SENDUCASTPKTPERCENT,SENDMCASTPKTPERCENT,SENDBCASTPKTPERCENT,
              SENDERRORS,SENDERRORPERCENT,SENDDISCARDS,SENDDISCARDPERCENT,RECEIVEUTIL,RECEIVETOTALPKTS,
              RECEIVETOTALPKTRATE,RECEIVEBYTES,RECEIVEBYTERATE,RECEIVEBITRATE,RECEIVEUCASTPKTPERCENT,
              RECEIVEMCASTPKTPERCENT,RECEIVEBCASTPKTPERCENT,RECEIVEERRORS,RECEIVEERRORPERCENT,RECEIVEDISCARDS,
              RECEIVEDISCARDPERCENT,SENDBCASTPKTRATE,RECEIVEBCASTPKTRATE,IFTYPESTRING,MAX_SEND_RECEIVE,
              ROW_NUMBER() OVER (PARTITION BY TRUNC(FECHA,'DAY'),
                                              NODE,
                                              INTERFAZ,
                                              IFINDEX,
                                              IFTYPE,
                                              IFTYPESTRING
                                  ORDER BY MAX_SEND_RECEIVE DESC) SEQNUM
      FROM CSCO_INTERFACE_BH
      --WHERE NODE = 'CRR-PE-R02'
     -- AND INTERFAZ = 'GigabitEthernet2/40'
      )
WHERE SEQNUM <= 3
AND TRUNC(FECHA) BETWEEN TO_DATE('01.01.2017','DD.MM.YYYY') AND TO_DATE('07.01.2017','DD.MM.YYYY') + 86399/86400
GROUP BY  FECHA,
          NODE,
          INTERFAZ,
          IFINDEX,
          IFTYPE,
          IFTYPESTRING;
