
CREATE TABLE EHEALTH_OBJECTS 
(
  ELEMENT_ID NUMBER NOT NULL
, ELEMENT_ALIASES VARCHAR2(100 BYTE) 
, VALID_START_DATE DATE 
, VALID_FINISH_DATE DATE 
, TIPO VARCHAR2(40 BYTE) 
, ORIGEN VARCHAR2(40 BYTE) 
, DESTINO VARCHAR2(40 BYTE) 
, FLAG_ENABLED VARCHAR2(1 BYTE) 
, GRUPO VARCHAR2(50 BYTE) 
, PAIS VARCHAR2(20 BYTE) 
, ELEMENT_TYPE VARCHAR2(20 BYTE) 
, ELEMENT_NAME VARCHAR2(20 BYTE) 
, INTERFACE_NAME VARCHAR2(100 BYTE) 
, GROUP_TYPE VARCHAR2(20 BYTE) 
, ELEMENT_IP VARCHAR2(15 BYTE) 
, NOMBRE_GRUPO VARCHAR2(50 BYTE) 
, FRONTERA VARCHAR2(30 BYTE) 
) ;

ALTER TABLE EHEALTH_OBJECTS ADD CONSTRAINT EHEALTH_OBJECTS_PK PRIMARY KEY (ELEMENT_ID); 

create table EHEALTH_STAT_IP_HOUR(
FECHA	              DATE NOT NULL,
ELEMENT_ID	        NUMBER NOT NULL,
BITS_IN	            NUMBER,
BITS_OUT	          NUMBER,
SPEED_MBPS	        NUMBER,
DISCARDS_IN	        NUMBER,
DISCARDS_OUT	      NUMBER,
ERRORS_IN	          NUMBER,
ERRORS_OUT	        NUMBER,
FRAMES_IN	          NUMBER,
FRAMES_OUT	        NUMBER,
NON_UNICAST_IN	    NUMBER,
NON_UNICAST_OUT	    NUMBER,
INPUT_QUEUE_DROPS	  NUMBER,
OUTPUT_QUEUE_DROPS	NUMBER,
LATENCY	            NUMBER,
AVAILABILITY	      NUMBER
);

/* ALTER TABLE SCOTT.EHEALTH_STAT_IP_HOUR
ADD CONSTRAINT EHEALTH_STAT_IP_HR_PK PRIMARY KEY 
(
  FECHA 
, ELEMENT_ID 
)
USING INDEX EHEALTH_STAT_IP_HR_PK
ENABLECREATE TABLE SCOTT.EHEALTH_STAT_IP_HOUR 
(
  FECHA DATE NOT NULL 
, ELEMENT_ID NUMBER(*, 0) NOT NULL 
, BITS_IN NUMBER 
, BITS_OUT NUMBER 
, SPEED_MBPS NUMBER 
, DISCARDS_IN NUMBER 
, DISCARDS_OUT NUMBER 
, ERRORS_IN NUMBER 
, ERRORS_OUT NUMBER 
, FRAMES_IN NUMBER 
, FRAMES_OUT NUMBER 
, NON_UNICAST_IN NUMBER 
, NON_UNICAST_OUT NUMBER 
, INPUT_QUEUE_DROPS NUMBER 
, OUTPUT_QUEUE_DROPS NUMBER 
, LATENCY NUMBER 
, AVAILABILITY NUMBER 
) 
TABLESPACE "TBS_SVA_HOURLY" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL 
PARTITION BY RANGE (FECHA) 
(
  PARTITION EHEALTH_STAT_IP_HR_2015121300 VALUES LESS THAN (TO_DATE(' 2015-12-13 01:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
  LOGGING 
  TABLESPACE "TBS_SVA_HOURLY" 
  PCTFREE 10 
  PCTUSED 80 
  INITRANS 1 
  STORAGE 
  ( 
    INITIAL 262144 
    NEXT 262144 
    MINEXTENTS 1 
    MAXEXTENTS UNLIMITED 
    PCTINCREASE 0 
    FREELISTS 1 
    FREELIST GROUPS 1 
    BUFFER_POOL DEFAULT 
  )  */