  CREATE TABLE FILES 
   (	NOMBRE_XML VARCHAR2(255 CHAR), 
	NOMBRE_CSV VARCHAR2(255 CHAR), 
	STATUS NUMBER(1,0) DEFAULT 5, 
	ROW_NUM NUMBER DEFAULT 0, 
	PROCESADO TIMESTAMP (6)
   )  ;

  CREATE UNIQUE INDEX PK_FILES ON FILES (NOMBRE_XML) ;


  ALTER TABLE FILES ADD CONSTRAINT PK_FILES PRIMARY KEY (NOMBRE_XML);
