CREATE TABLE IMPORT_LOG_DATA 
   (	NOMBRE_CSV VARCHAR2(500 CHAR) NOT NULL ENABLE, 
	BAD_FILE VARCHAR2(500 CHAR),
	SKIPPED NUMBER, 
	READED NUMBER, 
	REJECTED NUMBER, 
	DISCARDED NUMBER, 
	PROCESADO TIMESTAMP (6) NOT NULL ENABLE,  
	 CONSTRAINT IMPORT_LOG_DATA_PK PRIMARY KEY (NOMBRE_CSV, PROCESADO)) nologging;

   COMMENT ON COLUMN IMPORT_LOG_DATA.NOMBRE_CSV IS 'Nombre de archivo que dio error en la carga';
   COMMENT ON COLUMN IMPORT_LOG_DATA.SKIPPED IS 'Numero de registros evitados';
   COMMENT ON COLUMN IMPORT_LOG_DATA.READED IS 'Numero de registros leidos';
   COMMENT ON COLUMN IMPORT_LOG_DATA.REJECTED IS 'Numero de registros rechazados';
   COMMENT ON COLUMN IMPORT_LOG_DATA.DISCARDED IS 'Numero de registros descartados';
   COMMENT ON COLUMN IMPORT_LOG_DATA.PROCESADO IS 'Fecha en la que se proceso el archivo';
