
-- DROP TABLE INTERFACE_RAW;

CREATE TABLE CSCO_INTERFACE_HOUR (
FECHA                   DATE NOT NULL,
NODE                    VARCHAR2(20 CHAR) NOT NULL,
INTERFAZ                VARCHAR2(20 CHAR) NOT NULL,
IFINDEX                 NUMBER NOT NULL,
IFTYPE                  NUMBER NOT NULL,
IFSPEED                 NUMBER(24,2) NOT NULL,
SENDUTIL                NUMBER(4,2) NOT NULL,
SENDTOTALPKTS           NUMBER NOT NULL,
SENDTOTALPKTRATE        NUMBER(24,2) NOT NULL,
SENDBYTES               NUMBER NOT NULL,
SENDBYTERATE            NUMBER(24,2) NOT NULL,
SENDBITRATE             NUMBER(24,2) NOT NULL,
SENDUCASTPKTPERCENT     NUMBER(24,2) NOT NULL,
SENDMCASTPKTPERCENT     NUMBER(24,2) NOT NULL,
SENDBCASTPKTPERCENT     NUMBER(24,2) NOT NULL,
SENDERRORS              NUMBER(24,2) NOT NULL,
SENDERRORPERCENT        NUMBER(24,2) NOT NULL,
SENDDISCARDS            NUMBER(24,2) NOT NULL,
SENDDISCARDPERCENT      NUMBER(24,2) NOT NULL,
RECEIVEUTIL             NUMBER(24,2) NOT NULL,
RECEIVETOTALPKTS        NUMBER(24,2) NOT NULL,
RECEIVETOTALPKTRATE     NUMBER(24,2) NOT NULL,
RECEIVEBYTES            NUMBER(24,2) NOT NULL,
RECEIVEBYTERATE         NUMBER(24,2) NOT NULL,
RECEIVEBITRATE          NUMBER(24,2) NOT NULL,
RECEIVEUCASTPKTPERCENT  NUMBER(24,2) NOT NULL,
RECEIVEMCASTPKTPERCENT  NUMBER(24,2) NOT NULL,
RECEIVEBCASTPKTPERCENT  NUMBER(24,2) NOT NULL,
RECEIVEERRORS           NUMBER(24,2) NOT NULL,
RECEIVEERRORPERCENT     NUMBER(24,2) NOT NULL,
RECEIVEDISCARDS         NUMBER(24,2) NOT NULL,
RECEIVEDISCARDPERCENT   NUMBER(24,2) NOT NULL,
SENDBCASTPKTRATE        NUMBER(24,2) NOT NULL,
RECEIVEBCASTPKTRATE     NUMBER(24,2) NOT NULL,
IFTYPESTRING            VARCHAR2(20 CHAR) NOT NULL
);

COMMENT ON COLUMN CSCO_INTERFACE_HOUR.INTERFAZ IS 'Reemplazo del nombre INTERFACE por ser palabra reservada';
COMMENT ON COLUMN CSCO_INTERFACE_HOUR.FECHA IS 'Reemplazo del nombre TIMESTAMP por ser palabra reservada';


CREATE TABLE CSCO_INTERFACE_DAY (
FECHA                   DATE NOT NULL,
NODE                    VARCHAR2(20 CHAR) NOT NULL,
INTERFAZ                VARCHAR2(20 CHAR) NOT NULL,
IFINDEX                 NUMBER NOT NULL,
IFTYPE                  NUMBER NOT NULL,
IFSPEED                 NUMBER(24,2) NOT NULL,
SENDUTIL                NUMBER(4,2) NOT NULL,
SENDTOTALPKTS           NUMBER NOT NULL,
SENDTOTALPKTRATE        NUMBER(24,2) NOT NULL,
SENDBYTES               NUMBER NOT NULL,
SENDBYTERATE            NUMBER(24,2) NOT NULL,
SENDBITRATE             NUMBER(24,2) NOT NULL,
SENDUCASTPKTPERCENT     NUMBER(24,2) NOT NULL,
SENDMCASTPKTPERCENT     NUMBER(24,2) NOT NULL,
SENDBCASTPKTPERCENT     NUMBER(24,2) NOT NULL,
SENDERRORS              NUMBER(24,2) NOT NULL,
SENDERRORPERCENT        NUMBER(24,2) NOT NULL,
SENDDISCARDS            NUMBER(24,2) NOT NULL,
SENDDISCARDPERCENT      NUMBER(24,2) NOT NULL,
RECEIVEUTIL             NUMBER(24,2) NOT NULL,
RECEIVETOTALPKTS        NUMBER(24,2) NOT NULL,
RECEIVETOTALPKTRATE     NUMBER(24,2) NOT NULL,
RECEIVEBYTES            NUMBER(24,2) NOT NULL,
RECEIVEBYTERATE         NUMBER(24,2) NOT NULL,
RECEIVEBITRATE          NUMBER(24,2) NOT NULL,
RECEIVEUCASTPKTPERCENT  NUMBER(24,2) NOT NULL,
RECEIVEMCASTPKTPERCENT  NUMBER(24,2) NOT NULL,
RECEIVEBCASTPKTPERCENT  NUMBER(24,2) NOT NULL,
RECEIVEERRORS           NUMBER(24,2) NOT NULL,
RECEIVEERRORPERCENT     NUMBER(24,2) NOT NULL,
RECEIVEDISCARDS         NUMBER(24,2) NOT NULL,
RECEIVEDISCARDPERCENT   NUMBER(24,2) NOT NULL,
SENDBCASTPKTRATE        NUMBER(24,2) NOT NULL,
RECEIVEBCASTPKTRATE     NUMBER(24,2) NOT NULL,
IFTYPESTRING            VARCHAR2(20 CHAR) NOT NULL
);

COMMENT ON COLUMN CSCO_INTERFACE_DAY.INTERFAZ IS 'Reemplazo del nombre INTERFACE por ser palabra reservada';
COMMENT ON COLUMN CSCO_INTERFACE_DAY.FECHA IS 'Reemplazo del nombre TIMESTAMP por ser palabra reservada';

CREATE TABLE CSCO_INTERFACE_BH (
FECHA                   DATE NOT NULL,
NODE                    VARCHAR2(20 CHAR) NOT NULL,
INTERFAZ                VARCHAR2(20 CHAR) NOT NULL,
IFINDEX                 NUMBER NOT NULL,
IFTYPE                  NUMBER NOT NULL,
IFSPEED                 NUMBER(24,2) NOT NULL,
SENDUTIL                NUMBER(4,2) NOT NULL,
SENDTOTALPKTS           NUMBER NOT NULL,
SENDTOTALPKTRATE        NUMBER(24,2) NOT NULL,
SENDBYTES               NUMBER NOT NULL,
SENDBYTERATE            NUMBER(24,2) NOT NULL,
SENDBITRATE             NUMBER(24,2) NOT NULL,
SENDUCASTPKTPERCENT     NUMBER(24,2) NOT NULL,
SENDMCASTPKTPERCENT     NUMBER(24,2) NOT NULL,
SENDBCASTPKTPERCENT     NUMBER(24,2) NOT NULL,
SENDERRORS              NUMBER(24,2) NOT NULL,
SENDERRORPERCENT        NUMBER(24,2) NOT NULL,
SENDDISCARDS            NUMBER(24,2) NOT NULL,
SENDDISCARDPERCENT      NUMBER(24,2) NOT NULL,
RECEIVEUTIL             NUMBER(24,2) NOT NULL,
RECEIVETOTALPKTS        NUMBER(24,2) NOT NULL,
RECEIVETOTALPKTRATE     NUMBER(24,2) NOT NULL,
RECEIVEBYTES            NUMBER(24,2) NOT NULL,
RECEIVEBYTERATE         NUMBER(24,2) NOT NULL,
RECEIVEBITRATE          NUMBER(24,2) NOT NULL,
RECEIVEUCASTPKTPERCENT  NUMBER(24,2) NOT NULL,
RECEIVEMCASTPKTPERCENT  NUMBER(24,2) NOT NULL,
RECEIVEBCASTPKTPERCENT  NUMBER(24,2) NOT NULL,
RECEIVEERRORS           NUMBER(24,2) NOT NULL,
RECEIVEERRORPERCENT     NUMBER(24,2) NOT NULL,
RECEIVEDISCARDS         NUMBER(24,2) NOT NULL,
RECEIVEDISCARDPERCENT   NUMBER(24,2) NOT NULL,
SENDBCASTPKTRATE        NUMBER(24,2) NOT NULL,
RECEIVEBCASTPKTRATE     NUMBER(24,2) NOT NULL,
IFTYPESTRING            VARCHAR2(20 CHAR) NOT NULL
);

COMMENT ON COLUMN CSCO_INTERFACE_BH.INTERFAZ IS 'Reemplazo del nombre INTERFACE por ser palabra reservada';
COMMENT ON COLUMN CSCO_INTERFACE_BH.FECHA IS 'Reemplazo del nombre TIMESTAMP por ser palabra reservada';

CREATE TABLE CSCO_INTERFACE_IBHW (
FECHA                   DATE NOT NULL,
NODE                    VARCHAR2(20 CHAR) NOT NULL,
INTERFAZ                VARCHAR2(20 CHAR) NOT NULL,
IFINDEX                 NUMBER NOT NULL,
IFTYPE                  NUMBER NOT NULL,
IFSPEED                 NUMBER(24,2) NOT NULL,
SENDUTIL                NUMBER(4,2) NOT NULL,
SENDTOTALPKTS           NUMBER NOT NULL,
SENDTOTALPKTRATE        NUMBER(24,2) NOT NULL,
SENDBYTES               NUMBER NOT NULL,
SENDBYTERATE            NUMBER(24,2) NOT NULL,
SENDBITRATE             NUMBER(24,2) NOT NULL,
SENDUCASTPKTPERCENT     NUMBER(24,2) NOT NULL,
SENDMCASTPKTPERCENT     NUMBER(24,2) NOT NULL,
SENDBCASTPKTPERCENT     NUMBER(24,2) NOT NULL,
SENDERRORS              NUMBER(24,2) NOT NULL,
SENDERRORPERCENT        NUMBER(24,2) NOT NULL,
SENDDISCARDS            NUMBER(24,2) NOT NULL,
SENDDISCARDPERCENT      NUMBER(24,2) NOT NULL,
RECEIVEUTIL             NUMBER(24,2) NOT NULL,
RECEIVETOTALPKTS        NUMBER(24,2) NOT NULL,
RECEIVETOTALPKTRATE     NUMBER(24,2) NOT NULL,
RECEIVEBYTES            NUMBER(24,2) NOT NULL,
RECEIVEBYTERATE         NUMBER(24,2) NOT NULL,
RECEIVEBITRATE          NUMBER(24,2) NOT NULL,
RECEIVEUCASTPKTPERCENT  NUMBER(24,2) NOT NULL,
RECEIVEMCASTPKTPERCENT  NUMBER(24,2) NOT NULL,
RECEIVEBCASTPKTPERCENT  NUMBER(24,2) NOT NULL,
RECEIVEERRORS           NUMBER(24,2) NOT NULL,
RECEIVEERRORPERCENT     NUMBER(24,2) NOT NULL,
RECEIVEDISCARDS         NUMBER(24,2) NOT NULL,
RECEIVEDISCARDPERCENT   NUMBER(24,2) NOT NULL,
SENDBCASTPKTRATE        NUMBER(24,2) NOT NULL,
RECEIVEBCASTPKTRATE     NUMBER(24,2) NOT NULL,
IFTYPESTRING            VARCHAR2(20 CHAR) NOT NULL
);

COMMENT ON COLUMN CSCO_INTERFACE_IBHW.INTERFAZ IS 'Reemplazo del nombre INTERFACE por ser palabra reservada';
COMMENT ON COLUMN CSCO_INTERFACE_IBHW.FECHA IS 'Reemplazo del nombre TIMESTAMP por ser palabra reservada';


--
--PARTITION BY RANGE (TIMESTAMP_) 
--INTERVAL(NUMTODSINTERVAL (1, 'DAY'))
--(  
--  PARTITION INTERFACE_RAW_FIRST VALUES LESS THAN (TO_DATE('11.04.2016','dd.mm.yyyy'))
-- );
