
-- DROP TABLE MEMORY_RAW;

CREATE TABLE CSCO_MEMORY_HOUR(	
  FECHA         DATE NOT NULL, 
  NODE          VARCHAR2(255 CHAR) NOT NULL, 
  NOMBRE        VARCHAR2(255 CHAR) NOT NULL, 
  TIPO          NUMBER NOT NULL, 
  USEDBYTES     NUMBER NOT NULL, 
  FREEBYTES     NUMBER NOT NULL, 
  AVGUTIL       NUMBER(6,2) NOT NULL, 
  MAXUTIL       NUMBER(24,2) NOT NULL, 
  MAXFREEBYTES  NUMBER(24,2) NOT NULL
);

COMMENT ON COLUMN CSCO_MEMORY_HOUR.FECHA IS 'Reemplazo de la columna TIMESTAMP por ser palabra reservada';
COMMENT ON COLUMN CSCO_MEMORY_HOUR.NOMBRE IS 'Reemplazo de la columna NAME por ser palabra reservada';
COMMENT ON COLUMN CSCO_MEMORY_HOUR.TIPO IS 'Reemplazo de la columna TYPE por ser palabra reservada';


CREATE TABLE CSCO_MEMORY_DAY(	
  FECHA         DATE NOT NULL, 
  NODE          VARCHAR2(255 CHAR) NOT NULL, 
  NOMBRE        VARCHAR2(255 CHAR) NOT NULL, 
  TIPO          NUMBER NOT NULL, 
  USEDBYTES     NUMBER NOT NULL, 
  FREEBYTES     NUMBER NOT NULL, 
  AVGUTIL       NUMBER(6,2) NOT NULL, 
  MAXUTIL       NUMBER(24,2) NOT NULL, 
  MAXFREEBYTES  NUMBER(24,2) NOT NULL
);

COMMENT ON COLUMN CSCO_MEMORY_DAY.FECHA IS 'Reemplazo de la columna TIMESTAMP por ser palabra reservada';
COMMENT ON COLUMN CSCO_MEMORY_DAY.NOMBRE IS 'Reemplazo de la columna NAME por ser palabra reservada';
COMMENT ON COLUMN CSCO_MEMORY_DAY.TIPO IS 'Reemplazo de la columna TYPE por ser palabra reservada';

CREATE TABLE CSCO_MEMORY_BH(	
  FECHA         DATE NOT NULL, 
  NODE          VARCHAR2(255 CHAR) NOT NULL, 
  NOMBRE        VARCHAR2(255 CHAR) NOT NULL, 
  TIPO          NUMBER NOT NULL, 
  USEDBYTES     NUMBER NOT NULL, 
  FREEBYTES     NUMBER NOT NULL, 
  AVGUTIL       NUMBER(6,2) NOT NULL, 
  MAXUTIL       NUMBER(24,2) NOT NULL, 
  MAXFREEBYTES  NUMBER(24,2) NOT NULL
);

COMMENT ON COLUMN CSCO_MEMORY_BH.FECHA IS 'Reemplazo de la columna TIMESTAMP por ser palabra reservada';
COMMENT ON COLUMN CSCO_MEMORY_BH.NOMBRE IS 'Reemplazo de la columna NAME por ser palabra reservada';
COMMENT ON COLUMN CSCO_MEMORY_BH.TIPO IS 'Reemplazo de la columna TYPE por ser palabra reservada';

CREATE TABLE CSCO_MEMORY_IBHW(	
  FECHA         DATE NOT NULL, 
  NODE          VARCHAR2(255 CHAR) NOT NULL, 
  NOMBRE        VARCHAR2(255 CHAR) NOT NULL, 
  TIPO          NUMBER NOT NULL, 
  USEDBYTES     NUMBER NOT NULL, 
  FREEBYTES     NUMBER NOT NULL, 
  AVGUTIL       NUMBER(6,2) NOT NULL, 
  MAXUTIL       NUMBER(24,2) NOT NULL, 
  MAXFREEBYTES  NUMBER(24,2) NOT NULL
);

COMMENT ON COLUMN CSCO_MEMORY_IBHW.FECHA IS 'Reemplazo de la columna TIMESTAMP por ser palabra reservada';
COMMENT ON COLUMN CSCO_MEMORY_IBHW.NOMBRE IS 'Reemplazo de la columna NAME por ser palabra reservada';
COMMENT ON COLUMN CSCO_MEMORY_IBHW.TIPO IS 'Reemplazo de la columna TYPE por ser palabra reservada';


--PARTITION BY RANGE (TIMESTAMP_) 
--INTERVAL(NUMTODSINTERVAL (1, 'DAY'))
--(  
--  PARTITION MEMORY_RAW_FIRST VALUES LESS THAN (TO_DATE('11.04.2016','dd.mm.yyyy'))
-- );
