
-- DROP TABLE MEMORY_DEVICE_AVG_RAW;

CREATE TABLE CSCO_MEMORY_DEVICE_AVG_HOUR(
  FECHA               DATE NOT NULL,
  NODE                VARCHAR2(255 CHAR) NOT NULL,
  USEDBYTESDEVICEAVG  NUMBER NOT NULL,
  FREEBYTESDEVICEAVG  NUMBER NOT NULL,
  AVGUTILDEVICEAVG    NUMBER NOT NULL,
  MAXUTILDEVICEAVG    NUMBER NOT NULL
);

COMMENT ON COLUMN CSCO_MEMORY_DEVICE_AVG_HOUR.FECHA IS 'Reemplazo de la columna TIMESTAMP por ser palabra reservada';


CREATE TABLE CSCO_MEMORY_DEVICE_AVG_DAY(
  FECHA               DATE NOT NULL,
  NODE                VARCHAR2(255 CHAR) NOT NULL,
  USEDBYTESDEVICEAVG  NUMBER NOT NULL,
  FREEBYTESDEVICEAVG  NUMBER NOT NULL,
  AVGUTILDEVICEAVG    NUMBER NOT NULL,
  MAXUTILDEVICEAVG    NUMBER NOT NULL
);

COMMENT ON COLUMN CSCO_MEMORY_DEVICE_AVG_DAY.FECHA IS 'Reemplazo de la columna TIMESTAMP por ser palabra reservada';

CREATE TABLE CSCO_MEMORY_DEVICE_AVG_BH(
  FECHA               DATE NOT NULL,
  NODE                VARCHAR2(255 CHAR) NOT NULL,
  USEDBYTESDEVICEAVG  NUMBER NOT NULL,
  FREEBYTESDEVICEAVG  NUMBER NOT NULL,
  AVGUTILDEVICEAVG    NUMBER NOT NULL,
  MAXUTILDEVICEAVG    NUMBER NOT NULL
);

COMMENT ON COLUMN CSCO_MEMORY_DEVICE_AVG_BH.FECHA IS 'Reemplazo de la columna TIMESTAMP por ser palabra reservada';

CREATE TABLE CSCO_MEMORY_DEVICE_AVG_IBHW(
  FECHA               DATE NOT NULL,
  NODE                VARCHAR2(255 CHAR) NOT NULL,
  USEDBYTESDEVICEAVG  NUMBER NOT NULL,
  FREEBYTESDEVICEAVG  NUMBER NOT NULL,
  AVGUTILDEVICEAVG    NUMBER NOT NULL,
  MAXUTILDEVICEAVG    NUMBER NOT NULL
);

COMMENT ON COLUMN CSCO_MEMORY_DEVICE_AVG_IBHW.FECHA IS 'Reemplazo de la columna TIMESTAMP por ser palabra reservada';


--    PARTITION BY RANGE (TIMESTAMP_) 
--    INTERVAL(NUMTODSINTERVAL (1, 'DAY'))
--   (  
--    PARTITION MEMORY_DEVICE_AVG_RAW_29042016 VALUES LESS THAN (TO_DATE('29.04.2016','dd.mm.yyyy'))
--   );