--
--
--
CREATE TABLE CSCO_CPU_MEM_DEVICE_AVG_HOUR(
  FECHA	                  DATE NOT NULL,
  NODE	                  VARCHAR2(255 CHAR) NOT NULL,
  CPUUTILMAX5MINDEVICEAVG	NUMBER(15,2) NOT NULL,
  CPUUTILAVG5MINDEVICEAVG	NUMBER(15,2) NOT NULL,
  CPUUTILMAX1MINDEVICEAVG	NUMBER(15,2) NOT NULL,
  CPUUTILAVG1MINDEVICEAVG	NUMBER(15,2) NOT NULL,
  USEDBYTESDEVICEAVG	    NUMBER NOT NULL,
  FREEBYTESDEVICEAVG	    NUMBER NOT NULL,
  AVGUTILDEVICEAVG	      NUMBER NOT NULL,
  MAXUTILDEVICEAVG	      NUMBER NOT NULL
);

ALTER TABLE CSCO_CPU_MEM_DEVICE_AVG_HOUR ADD CONSTRAINT PK_CSCO_CPU_MEM_DEVICE_AVG_H PRIMARY KEY(FECHA,NODE);
COMMENT ON TABLE CSCO_CPU_MEM_DEVICE_AVG_HOUR IS 'Contiene los datos de la union de las tablas CSCO_CPU_DEVICE_AVG y CSCO_MEMORY_DEVICE_AVG unidos por FECHA, NODE';
COMMENT ON COLUMN CSCO_CPU_MEM_DEVICE_AVG_HOUR.FECHA IS 'Reemplazo de la columna TIMESTAMP por ser palabra reservada';

CREATE PUBLIC SYNONYM CSCO_CPU_MEM_DEVICE_AVG_HOUR FOR MCARRASCO.CSCO_CPU_MEM_DEVICE_AVG_HOUR;

--
--
--
CREATE TABLE CSCO_CPU_MEM_DEVICE_AVG_DAY(
  FECHA	                  DATE NOT NULL,
  NODE	                  VARCHAR2(255 CHAR) NOT NULL,
  CPUUTILMAX5MINDEVICEAVG	NUMBER(15,2) NOT NULL,
  CPUUTILAVG5MINDEVICEAVG	NUMBER(15,2) NOT NULL,
  CPUUTILMAX1MINDEVICEAVG	NUMBER(15,2) NOT NULL,
  CPUUTILAVG1MINDEVICEAVG	NUMBER(15,2) NOT NULL,
  USEDBYTESDEVICEAVG	    NUMBER NOT NULL,
  FREEBYTESDEVICEAVG	    NUMBER NOT NULL,
  AVGUTILDEVICEAVG	      NUMBER NOT NULL,
  MAXUTILDEVICEAVG	      NUMBER NOT NULL
);
ALTER TABLE CSCO_CPU_MEM_DEVICE_AVG_DAY ADD CONSTRAINT PK_CSCO_CPU_MEM_DEVICE_AVG_D PRIMARY KEY(FECHA,NODE);

COMMENT ON TABLE CSCO_CPU_MEM_DEVICE_AVG_DAY IS 'Contiene los datos de la union de las tablas CSCO_CPU_DEVICE_AVG y CSCO_MEMORY_DEVICE_AVG unidos por FECHA, NODE';
COMMENT ON COLUMN CSCO_CPU_MEM_DEVICE_AVG_DAY.FECHA IS 'Reemplazo de la columna TIMESTAMP por ser palabra reservada';

CREATE PUBLIC SYNONYM CSCO_CPU_MEM_DEVICE_AVG_DAY FOR MCARRASCO.CSCO_CPU_MEM_DEVICE_AVG_DAY;

--
--
--
CREATE TABLE CSCO_CPU_MEM_DEVICE_AVG_BH(
  FECHA	                  DATE NOT NULL,
  NODE	                  VARCHAR2(255 CHAR) NOT NULL,
  CPUUTILMAX5MINDEVICEAVG	NUMBER(15,2) NOT NULL,
  CPUUTILAVG5MINDEVICEAVG	NUMBER(15,2) NOT NULL,
  CPUUTILMAX1MINDEVICEAVG	NUMBER(15,2) NOT NULL,
  CPUUTILAVG1MINDEVICEAVG	NUMBER(15,2) NOT NULL,
  USEDBYTESDEVICEAVG	    NUMBER NOT NULL,
  FREEBYTESDEVICEAVG	    NUMBER NOT NULL,
  AVGUTILDEVICEAVG	      NUMBER NOT NULL,
  MAXUTILDEVICEAVG	      NUMBER NOT NULL
);

ALTER TABLE CSCO_CPU_MEM_DEVICE_AVG_BH ADD CONSTRAINT PK_CSCO_CPU_MEM_DEVICE_AVG_BH PRIMARY KEY(FECHA,NODE);

COMMENT ON TABLE CSCO_CPU_MEM_DEVICE_AVG_BH IS 'Contiene los datos de la union de las tablas CSCO_CPU_DEVICE_AVG y CSCO_MEMORY_DEVICE_AVG unidos por FECHA, NODE';
COMMENT ON COLUMN CSCO_CPU_MEM_DEVICE_AVG_BH.FECHA IS 'Reemplazo de la columna TIMESTAMP por ser palabra reservada';

CREATE PUBLIC SYNONYM CSCO_CPU_MEM_DEVICE_AVG_BH FOR MCARRASCO.CSCO_CPU_MEM_DEVICE_AVG_BH;

--
--
--
CREATE TABLE CSCO_CPU_MEM_DEVICE_AVG_IBHW(
  FECHA	                  DATE NOT NULL,
  NODE	                  VARCHAR2(255 CHAR) NOT NULL,
  CPUUTILMAX5MINDEVICEAVG	NUMBER(15,2) NOT NULL,
  CPUUTILAVG5MINDEVICEAVG	NUMBER(15,2) NOT NULL,
  CPUUTILMAX1MINDEVICEAVG	NUMBER(15,2) NOT NULL,
  CPUUTILAVG1MINDEVICEAVG	NUMBER(15,2) NOT NULL,
  USEDBYTESDEVICEAVG	    NUMBER NOT NULL,
  FREEBYTESDEVICEAVG	    NUMBER NOT NULL,
  AVGUTILDEVICEAVG	      NUMBER NOT NULL,
  MAXUTILDEVICEAVG	      NUMBER NOT NULL
);

ALTER TABLE CSCO_CPU_MEM_DEVICE_AVG_IBHW ADD CONSTRAINT PK_CSCO_CPU_MEM_DEVICE_AVG_IB PRIMARY KEY(FECHA,NODE);

COMMENT ON TABLE CSCO_CPU_MEM_DEVICE_AVG_IBHW IS 'Contiene los datos de la union de las tablas CSCO_CPU_DEVICE_AVG y CSCO_MEMORY_DEVICE_AVG unidos por FECHA, NODE';
COMMENT ON COLUMN CSCO_CPU_MEM_DEVICE_AVG_IBHW.FECHA IS 'Reemplazo de la columna TIMESTAMP por ser palabra reservada';

CREATE PUBLIC SYNONYM CSCO_CPU_MEM_DEVICE_AVG_IBHW FOR MCARRASCO.CSCO_CPU_MEM_DEVICE_AVG_IBHW;