--
--
--
CREATE TABLE CSCO_CPU_MEM_DEVICE_AVG_HOUR(
  FECHA	                  DATE NOT NULL,
  NODE	                  VARCHAR2(255 CHAR) NOT NULL,
  CPUUTILMAX5MINDEVICEAVG	NUMBER(15,2) NOT NULL,
  CPUUTILAVG5MINDEVICEAVG	NUMBER(15,2) NOT NULL,
  CPUUTILMAX1MINDEVICEAVG	NUMBER(15,2) NOT NULL,
  CPUUTILAVG1MINDEVICEAVG	NUMBER(15,2) NOT NULL,
  USEDBYTESDEVICEAVG	    NUMBER NOT NULL,
  FREEBYTESDEVICEAVG	    NUMBER NOT NULL,
  AVGUTILDEVICEAVG	      NUMBER NOT NULL,
  MAXUTILDEVICEAVG	      NUMBER NOT NULL
);

ALTER TABLE CSCO_CPU_MEM_DEVICE_AVG_HOUR ADD CONSTRAINT PK_CSCO_CPU_MEM_DEVICE_AVG_H PRIMARY KEY(FECHA,NODE);
COMMENT ON TABLE CSCO_CPU_MEM_DEVICE_AVG_HOUR IS 'Contiene los datos de la union de las tablas CSCO_CPU_DEVICE_AVG y CSCO_MEMORY_DEVICE_AVG unidos por FECHA, NODE';
COMMENT ON COLUMN CSCO_CPU_MEM_DEVICE_AVG_HOUR.FECHA IS 'Reemplazo de la columna TIMESTAMP por ser palabra reservada';

CREATE PUBLIC SYNONYM CSCO_CPU_MEM_DEVICE_AVG_HOUR FOR MCARRASCO.CSCO_CPU_MEM_DEVICE_AVG_HOUR;

--
--
--
CREATE TABLE CSCO_CPU_MEM_DEVICE_AVG_DAY(
  FECHA	                  DATE NOT NULL,
  NODE	                  VARCHAR2(255 CHAR) NOT NULL,
  CPUUTILMAX5MINDEVICEAVG	NUMBER(15,2) NOT NULL,
  CPUUTILAVG5MINDEVICEAVG	NUMBER(15,2) NOT NULL,
  CPUUTILMAX1MINDEVICEAVG	NUMBER(15,2) NOT NULL,
  CPUUTILAVG1MINDEVICEAVG	NUMBER(15,2) NOT NULL,
  USEDBYTESDEVICEAVG	    NUMBER NOT NULL,
  FREEBYTESDEVICEAVG	    NUMBER NOT NULL,
  AVGUTILDEVICEAVG	      NUMBER NOT NULL,
  MAXUTILDEVICEAVG	      NUMBER NOT NULL
);
ALTER TABLE CSCO_CPU_MEM_DEVICE_AVG_DAY ADD CONSTRAINT PK_CSCO_CPU_MEM_DEVICE_AVG_D PRIMARY KEY(FECHA,NODE);

COMMENT ON TABLE CSCO_CPU_MEM_DEVICE_AVG_DAY IS 'Contiene los datos de la union de las tablas CSCO_CPU_DEVICE_AVG y CSCO_MEMORY_DEVICE_AVG unidos por FECHA, NODE';
COMMENT ON COLUMN CSCO_CPU_MEM_DEVICE_AVG_DAY.FECHA IS 'Reemplazo de la columna TIMESTAMP por ser palabra reservada';

CREATE PUBLIC SYNONYM CSCO_CPU_MEM_DEVICE_AVG_DAY FOR MCARRASCO.CSCO_CPU_MEM_DEVICE_AVG_DAY;

--
--
--
CREATE TABLE CSCO_CPU_MEM_DEVICE_AVG_BH(
  FECHA	                  DATE NOT NULL,
  NODE	                  VARCHAR2(255 CHAR) NOT NULL,
  CPUUTILMAX5MINDEVICEAVG	NUMBER(15,2) NOT NULL,
  CPUUTILAVG5MINDEVICEAVG	NUMBER(15,2) NOT NULL,
  CPUUTILMAX1MINDEVICEAVG	NUMBER(15,2) NOT NULL,
  CPUUTILAVG1MINDEVICEAVG	NUMBER(15,2) NOT NULL,
  USEDBYTESDEVICEAVG	    NUMBER NOT NULL,
  FREEBYTESDEVICEAVG	    NUMBER NOT NULL,
  AVGUTILDEVICEAVG	      NUMBER NOT NULL,
  MAXUTILDEVICEAVG	      NUMBER NOT NULL
);

ALTER TABLE CSCO_CPU_MEM_DEVICE_AVG_BH ADD CONSTRAINT PK_CSCO_CPU_MEM_DEVICE_AVG_BH PRIMARY KEY(FECHA,NODE);

COMMENT ON TABLE CSCO_CPU_MEM_DEVICE_AVG_BH IS 'Contiene los datos de la union de las tablas CSCO_CPU_DEVICE_AVG y CSCO_MEMORY_DEVICE_AVG unidos por FECHA, NODE';
COMMENT ON COLUMN CSCO_CPU_MEM_DEVICE_AVG_BH.FECHA IS 'Reemplazo de la columna TIMESTAMP por ser palabra reservada';

CREATE PUBLIC SYNONYM CSCO_CPU_MEM_DEVICE_AVG_BH FOR MCARRASCO.CSCO_CPU_MEM_DEVICE_AVG_BH;

--
--
--
CREATE TABLE CSCO_CPU_MEM_DEVICE_AVG_IBHW(
  FECHA	                  DATE NOT NULL,
  NODE	                  VARCHAR2(255 CHAR) NOT NULL,
  CPUUTILMAX5MINDEVICEAVG	NUMBER(15,2) NOT NULL,
  CPUUTILAVG5MINDEVICEAVG	NUMBER(15,2) NOT NULL,
  CPUUTILMAX1MINDEVICEAVG	NUMBER(15,2) NOT NULL,
  CPUUTILAVG1MINDEVICEAVG	NUMBER(15,2) NOT NULL,
  USEDBYTESDEVICEAVG	    NUMBER NOT NULL,
  FREEBYTESDEVICEAVG	    NUMBER NOT NULL,
  AVGUTILDEVICEAVG	      NUMBER NOT NULL,
  MAXUTILDEVICEAVG	      NUMBER NOT NULL
);

ALTER TABLE CSCO_CPU_MEM_DEVICE_AVG_IBHW ADD CONSTRAINT PK_CSCO_CPU_MEM_DEVICE_AVG_IB PRIMARY KEY(FECHA,NODE);

COMMENT ON TABLE CSCO_CPU_MEM_DEVICE_AVG_IBHW IS 'Contiene los datos de la union de las tablas CSCO_CPU_DEVICE_AVG y CSCO_MEMORY_DEVICE_AVG unidos por FECHA, NODE';
COMMENT ON COLUMN CSCO_CPU_MEM_DEVICE_AVG_IBHW.FECHA IS 'Reemplazo de la columna TIMESTAMP por ser palabra reservada';

CREATE PUBLIC SYNONYM CSCO_CPU_MEM_DEVICE_AVG_IBHW FOR MCARRASCO.CSCO_CPU_MEM_DEVICE_AVG_IBHW;


/*
WITH  MAX_SENDBYTES AS  (SELECT NODE||','||FECHA NODE_FECHA,
                                    NODE,
                                    FECHA,
                                    SENDBYTES
                            FROM (SELECT  FECHA,
                                          NODE,
                                          SENDBYTES,
                                          ROW_NUMBER() OVER( PARTITION BY NODE,TRUNC(FECHA) ORDER BY SENDBYTES DESC) RN
                                  FROM (SELECT  
                                                FECHA,
                                                NODE,
                                                SENDBYTES,
                                                ROW_NUMBER() OVER( PARTITION BY NODE,FECHA ORDER BY SENDBYTES DESC) RNK 
                                        FROM CSCO_INTERFACE_HOUR
                                        WHERE TO_CHAR(FECHA,'DD.MM.YYYY') BETWEEN TO_DATE(FECHA_DESDE,'DD.MM.YYYY')
                                                AND TO_DATE(FECHA_HASTA, 'DD.MM.YYYY') + 86399/86400 --FECHA_DESDE AND FECHA_HASTA
                                      )
                                  WHERE RNK = 1
                                  ORDER BY SENDBYTES DESC)
                            WHERE RN = 1),
          MAX_RECEIVEBYTES AS (SELECT NODE||','||FECHA NODE_FECHA,
                                      NODE,
                                      FECHA,
                                      RECEIVEBYTES
                              FROM (SELECT  FECHA,
                                            NODE,
                                            RECEIVEBYTES,
                                            ROW_NUMBER() OVER( PARTITION BY NODE,TRUNC(FECHA) ORDER BY RECEIVEBYTES DESC) RN
                                    FROM (SELECT  
                                                  FECHA,
                                                  NODE,
                                                  RECEIVEBYTES,
                                                  ROW_NUMBER() OVER( PARTITION BY NODE,FECHA ORDER BY RECEIVEBYTES DESC) RNK 
                                          FROM CSCO_INTERFACE_HOUR
                                          WHERE TO_CHAR(FECHA,'DD.MM.YYYY')  BETWEEN TO_DATE(FECHA_DESDE,'DD.MM.YYYY')
                                                AND TO_DATE(FECHA_HASTA, 'DD.MM.YYYY') + 86399/86400 --FECHA_DESDE AND FECHA_HASTA
                                        )
                                    WHERE RNK = 1
                                    ORDER BY RECEIVEBYTES DESC)
                              WHERE RN = 1),
          PARES_NODE_FECHA  AS  (SELECT  CASE
                                          WHEN  MAX_SENDBYTES.SENDBYTES > MAX_RECEIVEBYTES.RECEIVEBYTES  THEN  MAX_SENDBYTES.NODE_FECHA
                                          WHEN  MAX_SENDBYTES.SENDBYTES < MAX_RECEIVEBYTES.RECEIVEBYTES  THEN  MAX_RECEIVEBYTES.NODE_FECHA
                                          ELSE  MAX_SENDBYTES.NODE_FECHA
                                        END NODE_FECHA
                                FROM  MAX_SENDBYTES,
                                      MAX_RECEIVEBYTES
                                WHERE MAX_SENDBYTES.NODE = MAX_RECEIVEBYTES.NODE
                                AND   MAX_SENDBYTES.FECHA = MAX_RECEIVEBYTES.FECHA)
    SELECT NODE_FECHA FROM PARES_NODE_FECHA
*/