
-- Autor: Mario Heredia.
-- Actualizacion: Mario Heredia. Fecha: 23.06.2009.
-- Actualizacion: Mario Heredia. Fecha: 28.12.2011. Motivo: Se cambia el tbs AUXILIAR por TBS_AUXILIAR. Se quitan COMMIT's innecesarios.
-- Actualizacion: Mauro Arraigada. Fecha: 01.07.2014. Motivo: se implementa variables bind.

--VARIABLE FECHA_DESDE VARCHAR2(15);
--VARIABLE FECHA_HASTA VARCHAR2(15);
--VARIABLE MASCARA     VARCHAR2(15);
--VARIABLE TR_HR       VARCHAR2(4);
--VARIABLE V_NUM       NUMBER;
--VARIABLE V_IN        VARCHAR2(4);
--VARIABLE V_OUT       VARCHAR2(4);
--
--EXEC :FECHA_DESDE := '&1';
--EXEC :FECHA_HASTA := '&2';
--EXEC :MASCARA     := 'DD.MM.YYYY';
--EXEC :TR_HR       := 'HH24';
--EXEC :V_NUM       := 1000;
--EXEC :V_IN        := 'IN';
--EXEC :V_OUT       := 'OUT';
--
--COLUMN C_HORA_INI   NEW_VALUE HORA_INI    NOPRINT;
--COLUMN C_HORA_FIN   NEW_VALUE HORA_FIN    NOPRINT;

SELECT MAX(HORA_INI) C_HORA_INI,
       MAX(HORA_FIN) C_HORA_FIN
  FROM (
SELECT DECODE(PRM_ID, 149, PRM_VALUE) HORA_INI,
       DECODE(PRM_ID, 150, PRM_VALUE) HORA_FIN
  FROM CALIDAD_PARAMETROS
 WHERE PRM_ID IN (149, 150)
       );

DROP TABLE AUX_EHEALTH_STAT_IP_BH PURGE;

CREATE TABLE AUX_EHEALTH_STAT_IP_BH TABLESPACE TBS_AUXILIAR PCTFREE 5 PCTUSED 95 AS
SELECT FECHA,
       ELEMENT_ID,
       BITS_IN,
       BITS_OUT,
       CANTIDAD_HORAS
  FROM (
		SELECT FECHA,
			   ELEMENT_ID,
			   BITS_IN,
			   BITS_OUT,
			   CANTIDAD_HORAS,
			   MAX(FECHA) OVER(PARTITION BY TRUNC(FECHA), ELEMENT_ID) MAX_FECHA
		  FROM (
				SELECT FECHA,
					   TRUNC_FECHA,
					   ELEMENT_ID,
					   BITS_IN,
					   BITS_OUT,
					   MAX_BITS_IN,
					   MAX_BITS_OUT,
					   CASE WHEN MAX_BITS_IN >= MAX_BITS_OUT THEN
								 MAX_BITS_IN
							ELSE MAX_BITS_OUT END MAX_BITS,
					   CASE WHEN MAX_BITS_IN >= MAX_BITS_OUT THEN
								 'IN'
							ELSE 'OUT' END MAX_USED,
					   CANTIDAD_HORAS
				  FROM (
						SELECT FECHA,
							   TRUNC(FECHA) TRUNC_FECHA,
							   ELEMENT_ID,
							   BITS_IN,
							   BITS_OUT,
							   MAX(BITS_IN) OVER(PARTITION BY TRUNC(FECHA), ELEMENT_ID) MAX_BITS_IN,
							   MAX(BITS_OUT) OVER(PARTITION BY TRUNC(FECHA), ELEMENT_ID) MAX_BITS_OUT,
							   COUNT(*) OVER(PARTITION BY TRUNC(FECHA), ELEMENT_ID) CANTIDAD_HORAS
						  FROM (
								SELECT A.FECHA,
									   A.ELEMENT_ID,
									   B.GRUPO,
									   A.BITS_IN,
									   A.BITS_OUT,
									   CASE WHEN TO_CHAR(FECHA, 'HH24') NOT BETWEEN &HORA_INI AND &HORA_FIN AND GRUPO = 'CAC' THEN 0 ELSE 1 END FLAG
								  FROM EHEALTH_STAT_IP_HOUR A,
									   EHEALTH_OBJECTS      B
								 WHERE FECHA BETWEEN TO_DATE('&1', 'DD.MM.YYYY')
												 AND TO_DATE('&2', 'DD.MM.YYYY') + 86399/86400
								   AND A.ELEMENT_ID = B.ELEMENT_ID
								   AND ROUND(((A.BITS_IN / 1000) / 1000), 2) <= A.SPEED_MBPS
								 ORDER BY GRUPO, FECHA
									   )
						 WHERE FLAG = 1
					   )
			   )
		 WHERE MAX_BITS = DECODE(MAX_USED, 'IN', BITS_IN, 'OUT', BITS_OUT)
		   AND TRUNC(FECHA) = TRUNC_FECHA
			   )
 WHERE FECHA = MAX_FECHA;

DELETE FROM EHEALTH_STAT_IP_BH
 WHERE FECHA BETWEEN TO_DATE(:FECHA_DESDE , :MASCARA)
                 AND TO_DATE(:FECHA_HASTA , :MASCARA) + 86399/86400;

INSERT INTO EHEALTH_STAT_IP_BH
(
  FECHA,
  ELEMENT_ID,
  BITS_IN,
  BITS_OUT,
  SPEED_MBPS,
  DISCARDS_IN,
  DISCARDS_OUT,
  ERRORS_IN,
  ERRORS_OUT,
  FRAMES_IN,
  FRAMES_OUT,
  NON_UNICAST_IN,
  NON_UNICAST_OUT,
  INPUT_QUEUE_DROPS,
  OUTPUT_QUEUE_DROPS,
  LATENCY,
  AVAILABILITY,
  CANTIDAD_HORAS
)
SELECT A.FECHA,
       A.ELEMENT_ID,
       A.BITS_IN,
       A.BITS_OUT,
       A.SPEED_MBPS,
       A.DISCARDS_IN,
       A.DISCARDS_OUT,
       A.ERRORS_IN,
       A.ERRORS_OUT,
       A.FRAMES_IN,
       A.FRAMES_OUT,
       A.NON_UNICAST_IN,
       A.NON_UNICAST_OUT,
       A.INPUT_QUEUE_DROPS,
       A.OUTPUT_QUEUE_DROPS,
       A.LATENCY,
       A.AVAILABILITY,
       CANTIDAD_HORAS
  FROM EHEALTH_STAT_IP_HOUR   A,
       AUX_EHEALTH_STAT_IP_BH B
 WHERE A.FECHA = B.FECHA
   AND A.ELEMENT_ID = B.ELEMENT_ID
   AND A.FECHA BETWEEN TO_DATE(:FECHA_DESDE , :MASCARA)
                   AND TO_DATE(:FECHA_HASTA , :MASCARA) + 86399/86400;

COMMIT;

EXIT;

--
-- DAY
--
-- Autor: Mario Heredia.
-- Actualizacion: Mario Heredia. Fecha: 29.01.2009.
-- Actualizacion: Mario Heredia. Fecha: 28.12.2011. Motivo: Se quitan COMMIT's innecesarios.
-- Actualizacion: Mauro Arraigada. Fecha: 01.07.2014. Motivo: se implementa variables bind.

VARIABLE FECHA_DESDE VARCHAR2(15);
VARIABLE FECHA_HASTA VARCHAR2(15);
VARIABLE MASCARA     VARCHAR2(15);

EXEC :FECHA_DESDE := '&1';
EXEC :FECHA_HASTA := '&2';
EXEC :MASCARA     := 'DD.MM.YYYY';


DELETE FROM EHEALTH_STAT_IP_DAY
 WHERE FECHA BETWEEN TO_DATE(:FECHA_DESDE , :MASCARA)
                 AND TO_DATE(:FECHA_HASTA , :MASCARA) + 86399/86400;

INSERT INTO EHEALTH_STAT_IP_DAY
(
  FECHA,
  ELEMENT_ID,
  BITS_IN,
  BITS_OUT,
  SPEED_MBPS,
  DISCARDS_IN,
  DISCARDS_OUT,
  ERRORS_IN,
  ERRORS_OUT,
  FRAMES_IN,
  FRAMES_OUT,
  NON_UNICAST_IN,
  NON_UNICAST_OUT,
  INPUT_QUEUE_DROPS,
  OUTPUT_QUEUE_DROPS,
  LATENCY,
  AVAILABILITY,
  CANTIDAD_HORAS
)
SELECT TRUNC(FECHA) FECHA,
       ELEMENT_ID,
       ROUND(AVG(BITS_IN), 2)      BITS_IN,
       ROUND(AVG(BITS_OUT), 2)     BITS_OUT,
       ROUND(AVG(SPEED_MBPS), 2)   SPEED_MBPS,
       SUM(DISCARDS_IN)            DISCARDS_IN,
       SUM(DISCARDS_OUT)           DISCARDS_OUT,
       SUM(ERRORS_IN)              ERRORS_IN,
       SUM(ERRORS_OUT)             ERRORS_OUT,
       SUM(FRAMES_IN)              FRAMES_IN,
       SUM(FRAMES_OUT)             FRAMES_OUT,
       SUM(NON_UNICAST_IN)         NON_UNICAST_IN,
       SUM(NON_UNICAST_OUT)        NON_UNICAST_OUT,
       SUM(INPUT_QUEUE_DROPS)      INPUT_QUEUE_DROPS,
       SUM(OUTPUT_QUEUE_DROPS)     OUTPUT_QUEUE_DROPS,
       ROUND(AVG(LATENCY), 2)      LATENCY,
       ROUND(AVG(AVAILABILITY), 2) AVAILABILITY,
       COUNT(*)                    CANTIDAD_HORAS
  FROM EHEALTH_STAT_IP_HOUR
 WHERE FECHA BETWEEN TO_DATE(:FECHA_DESDE , :MASCARA)
                 AND TO_DATE(:FECHA_HASTA , :MASCARA) + 86399/86400
 GROUP BY TRUNC(FECHA),
          ELEMENT_ID;

COMMIT;

EXIT;