
SELECT  CIH.NODE,CIH.FECHA,
        --ELEMENT_ID,
        ROUND(NVL(CIH.RECEIVEBYTES,0)*8/3600,2) RECEIVEBYTES,
        ROUND(NVL(CIH.SENDBYTES,0)*8/3600,2)  SENDBYTES,
        ROUND(NVL(CIH.IFSPEED,0)/1000/1000,2) IFSPEED,
        ROUND(NVL(CIH.RECEIVEDISCARDS,0)/3600,2) RECEIVEDISCARDS,
        ROUND(NVL(CIH.SENDDISCARDS,0)/3600,2) SENDDISCARDS,
        CIH.RECEIVEERRORS,
        CIH.SENDERRORS,
        CIH.RECEIVETOTALPKTRATE,
        CIH.SENDTOTALPKTRATE,
        --
        CIEH.INQUEUEDROPS,
        CIEH.OUTQUEUEDROPS,
        --
        CIAH.UPPERCENT,
        --
        CIH.SENDUTIL,
        CIH.SENDTOTALPKTS,
        CIH.SENDUCASTPKTPERCENT,
        CIH.SENDMCASTPKTPERCENT,
        CIH.SENDBCASTPKTPERCENT,
        CIH.SENDERRORPERCENT,
        CIH.SENDDISCARDPERCENT,
        CIH.RECEIVEUTIL,
        CIH.RECEIVETOTALPKTS,
        CIH.RECEIVEUCASTPKTPERCENT,
        CIH.RECEIVEMCASTPKTPERCENT,
        CIH.RECEIVEBCASTPKTPERCENT,
        CIH.RECEIVEERRORPERCENT,
        CIH.RECEIVEDISCARDPERCENT,
        CIH.SENDBCASTPKTRATE,
        CIH.RECEIVEBCASTPKTRATE
FROM  CSCO_INTERFACE_HOUR CIH,
      CSCO_INTERFACE_ERRORS_HOUR CIEH,
      CSCO_INTERFACE_AVAIL_HOUR CIAH,
      CSCO_INVENTORY INV
WHERE CIH.FECHA         = CIEH.FECHA
AND   CIH.NODE          = CIEH.NODE
AND   CIH.INTERFAZ      = CIEH.IFEXTIFDESCR
AND   CIEH.FECHA        = CIAH.FECHA
AND   CIEH.NODE         = CIAH.NODE
AND   CIEH.IFEXTIFDESCR = CIAH.INTERFACE_DISP
AND   CIH.FECHA = TO_DATE('20.08.2016 23:00:00')
AND   INV.DEVICE = CIH.NODE
AND   INV.DEVICE = 'AMB037-AGG-03'
;
--AND   TO_DATE(TO_CHAR(CIH.FECHA,'DD.MM.YYYY'),'DD.MM.YYYY') = TO_DATE('21.08.2016','DD.MM.YYYY');
